### ISSUE TITLE
Add rows to GOF block more easily

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#1]
Make it easier to add rows to the GOF block. Currently, users have to save the results in an intermediate ``texreg`` object and manipulate the ``gof``, ``gof.names``, and ``gof.decimal`` slots and then hand over the updated object to ``texreg``. This could be done more easily using dedicated arguments, such as ``add.decimal.gof`` and ``add.integer.gof``, which would expect a named list of values.

**Comment by alanpaulkwan** [comment]
I have modified your function to do this, if you want me to share.

**Comment by leifeld** [comment]
@alanpaulkwan That would be fantastic! Thanks!

**Comment by nfultz** [comment]
What is the right/best way to do this? Asking for https://stackoverflow.com/questions/50507650/texreg-on-panelmodel-plm-object-additional-gof-information

**Comment by leifeld** [comment]
I think the answer you have given there is probably the most elegant way to do it. That's at least how I would have done it. Or just edit the original function. If you'd like to include the F-statistic etc. in the `texreg` package by default, you can edit the `extract.plm` function in the package and I'm happy to accept a pull request. The answer by jaySf is also valid, but less elegant.
