### ISSUE TITLE
Extension for gnm objects

### ISSUE THREAD

**Issue by string-token** [leifeld/texreg#104]
The [gnm package](https://github.com/hturner/gnm/) offers functions for estimating generalized non-linear models like a non-linear extension of the glm package. As gnm syntax mimics the glm syntax, the glm extension for texreg would be able to grab some important model parameters. However, one is typically interested in slightly different GOF parameters like the degrees of freedom or the AIC for the deviance/L2 of the model in question. Thus, gnm would need its own extension.

**Comment by leifeld** [comment]
Addressed by #110.
