### ISSUE TITLE
Error nobs btergm

### ISSUE THREAD

**Issue by czucca** [leifeld/texreg#111]
Hi Philip, 

I checked the nobs btergm error and I need to make sure I understand the definition correctly.

in any IID model  nobs is the number of respondents. 

if in the tergm by nobs you mean the number of nodes, it is easy to fix the problem:
currently

`nobs <- model@nobs`

but to get the number of nodes I would simply put:

`nobs <- model@nvertices`

I checked on other models for comparison. 
- in extract.ergm nobs is not provided
- in stergm nobs is not provided but there is include.nvertices

I'm actually not sure what model@nobs is catching in btergm as it increases after inserting each covariate in the model. 

I also thought that nobs might refer to the number of unit in time considered in the temporal ergm, but
in btergm/btergm.r 

lines 116  and 117
`n <- object@nobs`
`t <- object@time.steps`

so this should exclude that nobs is the n of unit in time. 

in btergm/gofstatistics.R 

`n <- nrow * ncol`

so, provided that I'm reading it correctly and this refers to nobs, it would make sense the fact that nobs increases as the number of covariates increases since the matrix considered in the bootstraping increases in size as the number of variables increases. 

can you please clarify?

Thanks, 
Claudia

**Comment by leifeld** [comment]
Fixed in version 1.9.4 of `btergm`.
