### ISSUE TITLE
dcolumn + single.row fail when stars = numeric(0)

### ISSUE THREAD

**Issue by laravomfell** [leifeld/texreg#116]
When stars is set to `numeric(0)`, i.e. dropped, `single.row = TRUE` and `dcolumn = TRUE` result in an error in the calculation of the right.side (returning -Inf). The call still returns latex output but that cannot be used. This problem only occurs when `dcolumn` and `single.row` are both set to `TRUE`. 

An example:
```
data(iris)

texreg(lm(Sepal.Width ~ Petal.Width, data = iris), single.row = TRUE, dcolumn = TRUE, stars = numeric(0))
```
throws the following warning `Warning message: In max(nchar(right.side), na.rm = TRUE) :  no non-missing arguments to max; returning -Inf` and the first few line of the output are as follows:
```
\begin{table}
\begin{center}
\begin{tabular}{l D{)}{)}{11)-Inf} }
\hline
 & \multicolumn{1}{c}{Model 1} \\
\hline
(Intercept) & 3.31 \; (0.06)  \\
Petal.Width & -0.21 \; (0.04) \\
```

I tried to figure out where in the strsplit call for the right.side the problem emerges but it wasn't immediately obvious to me.

**Comment by leifeld** [comment]
Thanks. Which version is this? From CRAN or the current commit 9d0d58684c0edbc4ad92d54e3bd744610d9f12cb?

**Comment by laravomfell** [comment]
The issue occurred with the CRAN version. Just reran it using the current commit and that works:

```
\begin{table}
\begin{center}
\begin{tabular}{l D{)}{)}{15)1} }
\hline
 & \multicolumn{1}{c}{Model 1} \\
\hline
(Intercept) & 3.31 \; (0.06)  \\
```

**Comment by leifeld** [comment]
Great. I'll close this issue for now since it seems to have been addressed with recent changes. But feel free to reopen if problems persist or reappear.

**Comment by laravomfell** [comment]
The issue of `-Inf` has reappeared again as of commit `978d0bd`. The commits between that one and `9d0d586` referenced above work, every commit past `978d0bd` including the current commit produces this error again.

```
\begin{table}
\begin{center}
\begin{tabular}{l D{)}{)}{16)-Inf} }
\hline
 & \multicolumn{1}{c}{Model 1} \\
\hline
(Intercept) &   3.31 \; (0.06) \\
```

**Comment by leifeld** [comment]
I recently restructured the package and fixed a number of issues. It must have re-appeared while doing this. I'll take a look soon. Thanks.
