### ISSUE TITLE
dcolumn column width is computed incorrectly

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#119]
Somewhere between version 1.36.23 on CRAN and commit 9d0d58684c0edbc4ad92d54e3bd744610d9f12cb, the computation of column widths with the `dcolumn` package has been corrupted.

In the 2013 JSS articles, Table 3 and the corresponding LaTeX output in Section 5.2 have the following widths:

```
\begin{tabular}{l D{.}{.}{2.5}@{} D{.}{.}{2.5}@{} }
```
The same example currently produces the following output, with much wider columns:
```
\begin{tabular}{l D{.}{.}{10.8} D{.}{.}{10.8} }
```

**Comment by leifeld** [comment]
This problem now produces travis errors because the unit tests (commit 8e9ef829f1162763a0111545905de7f4ab5892db) based on the 2013 JSS article fail. When the issue is fixed, the unit tests must be reviewed and updated if necessary.

**Comment by leifeld** [comment]
The issue is caused by the `matrixreg` function not trimming the leading and trailing white space from the output matrix. I will fix this now, but I will defer the fix of the unit test to a later time once I have reviewed the remaining parts of the `texreg` function to ensure there are no other problems.

**Comment by czucca** [comment]
Hi Philip, I should have done this one. Thanks a lot!!!
