### ISSUE TITLE
Check LaTeX compatibility of row labels automatically

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#12]
Comment by user [ashenkin](https://r-forge.r-project.org/forum/forum.php?thread_id=31709&forum_id=4325&group_id=1420) (Alexander Shenkin) on R-Forge:

Hi there,

The predictors in my models often have underscores. This seems to lead to illegal TEX, as the underscores don't get escaped by ``texreg``. Is there any way to get ``texreg`` to automatically escape such characters when it produces the table, or will I have to make custom names?

thanks,
alex

```
my_df = data.frame(a = runif(100), b = runif(100), c_d = rep(c("a","b"),50))
my_mod = lmer(a ~ b + (1|c_d), data = my_df)
texreg(my_mod)
```
```
\begin{table}
\begin{center}
\begin{tabular}{l c }
\hline
& Model 1 \\
\hline
(Intercept) & $0.45^{***}$ \\
& $(0.05)$ \\
b & $0.12$ \\
& $(0.10)$ \\
\hline
AIC & 45.63 \\
BIC & 56.05 \\
Log Likelihood & -18.82 \\
Num. obs. & 100 \\
Num. groups: c_d & 2 \\
Variance: c_d.(Intercept) & 0.00 \\
Variance: Residual & 0.08 \\
\hline
\multicolumn{2}{l}{\scriptsize{$^{***}p<0.001$, $^{**}p<0.01$, $^*p<0.05$}}
\end{tabular}
\caption{Statistical models}
\label{table:coefficients}
\end{center}
\end{table}
```

**Comment by czucca** [comment]
closed by PR leifeld#86
