### ISSUE TITLE
Streamline the package structure wrt internal functions

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#122]
Currently, many functions in `internal.R` are only called once. Their body code should be moved directly to the respective place where the computation is needed. Ultimately, this may possibly mean moving most internal functions into `matrixreg`.

**Comment by leifeld** [comment]
Done with most of the restructuring. The online change that is still pending is that PR #117 needs to drop the `replaceSymbols` function and instead employ the new `names2latex` function. @czucca: Can you do this in your PR and delete the `replaceSymbols` function as part of your pull request and close this issue in your commit? Thanks.

**Comment by czucca** [comment]
Hi Philip, 

I'm not using `ReplaceSymbols` in `plotreg`, but sure I'm happy to delete the function and close this issue in my PR.

Also, I noticed that you deleted the `custommap` function, which I was using. Hence,

```
m1 <- lm(mpg ~ wt + cyl + carb, data=mtcars)

screenreg(m1, custom.coef.map = list("wt" = "var_1", "carb" = "var_2"))
```
prints the equivalent of `screenreg(m1)`

please let me know if you are planning on permanently remove `custommap`, so I will write an alternative.

**Comment by leifeld** [comment]
Oops. I have fixed the `custom.coef.map` argument of the `matrixreg` function now in commit 4652472ef725d05396d28afcaa40962c9f5563e9. One line was missing there.

If you need this updated code, you can either move it into a function (if it is a sufficient number of lines for it to be worth it) or duplicate the code (if it's just a few lines of code that you need).

Thanks for letting me know you don't need `replaceSymbols`. I have removed it now in commit b31b291ad4acbfbfd746287135c1f3f16f0927d4.

**Comment by czucca** [comment]
Ok, thanks! I'll check what works best and implement it!
