### ISSUE TITLE
Use roxygen2 for package documentation

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#123]
Move the current manual documentation to `roxygen2`.

**Comment by leifeld** [comment]
Finished documentation of everything apart from the `extract.R` file. I have added `roxygen2` markup for the generic `extract` function and the `lm`, `dynlm`, `ivreg`, and `speedglm` methods and saved them in a new git branch called `roxygenize-extract`. I have created this branch because the R check fails as long as the documentation of the whole file is not complete. In this branch, we need to document the remaining methods in a similar way as the `lm` etc. methods. @czucca: When you have finished PR #117, would you be willing to contribute to this, following my examples? Thanks.

**Comment by czucca** [comment]
of course! I'm very happy to contribute following your example!

**Comment by czucca** [comment]
Hi Philip, 

ok, I opened the extract.R in branch roxygenize-extract so I can start. I've seen a couple of functions are already done. Two questions

1) do you want the roxygenize markdown before or after the extract function? It's not clear from the current examples.
2) why two of them have `#' @noRd` before the function and the markdown text after? Lines 1197 and 2182. 

Thanks

**Comment by leifeld** [comment]
Great! I am currently working on `lmer` from the `lme4` package.

The markup needs to document the `setMethods` call, not the function body itself. The function body is no longer exported, only the method for the generic function is. Therefore we should roxygenize the `setMethods` call and add a `#' @noRd` tag to the functions themselves as the are only used internally to save the code. Does that make sense?

**Comment by czucca** [comment]
yes, I'll start from the top (Arima etc..) and do a couple of them. Then I'll make a PR so you can take a look and if it isn't correct you can stop me and I can fix it right after. Does this plan work? 

If you want, you can leave this entirely to me and take care of something else.

**Comment by leifeld** [comment]
Sounds good, thanks!

I'll finish the `lme4` code for now.

**Comment by leifeld** [comment]
Done with all roxygen2 documentation.
