### ISSUE TITLE
Improve code coverage in unit testing

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#124]
Create badge for code coverage on GitHub page. Then add further tests to `testthat` to ensure most of the code is tested.

**Comment by czucca** [comment]
After I finish roxygenizing the extract functions I can help with this too.

**Comment by leifeld** [comment]
Great! I have started working on the `roxygen2` markup and the unit tests at the same time. Every time I add documentation to an extract method, I also add a unit test from the help page of the respective model. But up to you of course.

**Comment by czucca** [comment]
Ah sure, I can do that too! ... just one thought... don't you think that if we both work on two files at the same time this could generate more conflicts?

**Comment by leifeld** [comment]
I'll work on other stuff, apart from the `lme4` methods.

**Comment by czucca** [comment]
by other stuff you mean the tests?

**Comment by leifeld** [comment]
No, I'll focus on other issues (that is, if I have enough time this week).

**Comment by czucca** [comment]
ok!

**Comment by leifeld** [comment]
I have added the infrastructure for unit testing and added a few tests for `extract` functions. It would be too tedious to go through each and every function now to increase code coverage. Instead, I will add a new test every time a function is changed or revisited in any way, so we should achieve an increasingly higher percentage over time through this without too much hassle.

**Comment by czucca** [comment]
it sounds like the best solution!
