### ISSUE TITLE
extract method for feisr::feis() 

### ISSUE THREAD

**Issue by ruettenauer** [leifeld/texreg#127]
Dear Philip,

First, thanks a lot for your great package!

I recently published the package feisr, providing the function feis() wich estimates fixed effects individual slopes models (a more general version of the well known FE models). The package also has an unexported extract function to use the model results with texreg (actually I just made some changes to the plm extract method). Do you think it might be possible to implement the feis extract method in the package texreg? 

I would be very happy if feis() could be used with texreg by default. Please see the code below.

Best,
Tobias

```R
extract.feis <- function(model, include.rsquared = TRUE, include.adjrs = TRUE,
                         include.nobs = TRUE, include.groups = TRUE,
                         include.rmse = TRUE, ...) {
  s <- summary(model, ...)

  coefficient.names <- rownames(coef(s))
  coefficients <- coef(s)[, 1]
  standard.errors <- coef(s)[, 2]
  significance <- coef(s)[, 4]

  rs <- s$r.squared[1]
  adj <- s$r.squared[2]
  n <- length(model$residuals)

  gof <- numeric()
  gof.names <- character()
  gof.decimal <- logical()
  if (include.rsquared == TRUE) {
    gof <- c(gof, rs)
    gof.names <- c(gof.names, "R$^2$")
    gof.decimal <- c(gof.decimal, TRUE)
  }
  if (include.adjrs == TRUE) {
    gof <- c(gof, adj)
    gof.names <- c(gof.names, "Adj.\ R$^2$")
    gof.decimal <- c(gof.decimal, TRUE)
  }
  if (include.nobs == TRUE) {
    gof <- c(gof, n)
    gof.names <- c(gof.names, "Num.\ obs.")
    gof.decimal <- c(gof.decimal, FALSE)
  }
  if (include.groups == TRUE) {
    grps <-length(unique(model$id))
    grp.names <- model$call[[match(c("id"), names(model$call))]]
    grp.names <- paste("Num.\ groups:", grp.names)
    gof <- c(gof, grps)
    gof.names <- c(gof.names, grp.names)
    gof.decimal <- c(gof.decimal, FALSE)
  }
  if (include.rmse == TRUE) {
    rmse <- sqrt(sum((model$residuals * model$residuals)) / model$df.residual)
    gof <- c(gof, rmse)
    gof.names <- c(gof.names, "RMSE")
    gof.decimal <- c(gof.decimal, TRUE)
  }

  tr <- texreg::createTexreg(
    coef.names = coefficient.names,
    coef = coefficients,
    se = standard.errors,
    pvalues = significance,
    gof.names = gof.names,
    gof = gof,
    gof.decimal = gof.decimal
  )
  return(tr)
}
```

**Comment by leifeld** [comment]
Thanks a lot for contributing this method. We will add it soon.

**Comment by leifeld** [comment]
We have started including unit tests with all new code that we include. Can you supply an example for your extract method that we can include? This is to make sure the extract method continues to work even if you change your package. Thanks.

**Comment by ruettenauer** [comment]
Great, thank you very much! Sure, please find an example below using the built-in dataset. I hope that's sufficient. Please let me know if you require any modifications or additional examples.
Best, Tobias

```R
library(feisr)
library(texreg)

setMethod("extract", signature = className("feis", "feisr"),
          definition = feisr:::extract.feis)

data("mwp", package = "feisr")
feis1.mod <- feis(lnw ~ marry
                  | exp, data = mwp, id = "id")
feis2.mod <- feis(lnw ~ marry + enrol + as.factor(yeargr)
                  | exp, data = mwp, id = "id")

sr1 <- screenreg(list(feis1.mod, feis2.mod), digits = 3)
tr1 <- texreg(list(feis1.mod, feis2.mod), digits = 3)
```

**Comment by leifeld** [comment]
Thanks again. I have added everything to the `roxygenize-extract` branch. I will merge this into the `master` branch once we have completed the remaining documentation in the `extract.R` file in a couple of weeks. The new version will then be rolled out to CRAN in a few months after a few more changes.

**Comment by ruettenauer** [comment]
Great, thanks a lot!
