### ISSUE TITLE
Unable to insert values in new gof row and properly display custom gof name

### ISSUE THREAD

**Issue by jasonjb82** [leifeld/texreg#128]
Using the lines below

```
map <- list("cert_now" = "Certified",
            "pccp" = "Certified share of local capacity",
            "factor(kh_class)1" = "NA",
            "factor(kh_class)2" = "NA",
            "pccp:factor(kh_class)1" = "NA",
            "pccp:factor(kh_class)2" = "NA",
            "g_cert_shr" = "Certified share of parent company’s holdings",
            "g_cert_shr:factor(kh_class)1" = "NA",
            "g_cert_shr:factor(kh_class)2" = "NA",
            "factor(kh_class)1:g_cert_shr" = "NA",
            "factor(kh_class)2:g_cert_shr" = "NA")

# Create regression table
htmlreg(list(cert.bife,pcc.bife,pcckh.bife,gc.bife,gckh.bife,all.bife,allkh.bife),
          omit.coef = "(Kalimantan)|(year)|(temp)|(precip)|(mcap)",
          custom.gof.rows = list("Year Fixed Effects" = c("Yes","Yes","Yes","Yes","Yes","Yes","Yes"),"Management Unit Fixed Effects" = c(1:7)),
          custom.model.names = c("Deforestation","Deforestation","Deforestation","Deforestation","Deforestation","Deforestation","Deforestation"),
          digits =5,caption="Spillovers",caption.above=TRUE,
          custom.coef.map = map,
          custom.note = "%stars. t statistics in parentheses",
          file = paste(wdir,"spillover_regression_table.doc"),inline.css = FALSE, doctype = TRUE, html.tag = TRUE, 
          head.tag = TRUE, body.tag = TRUE,indentation = "")
```
gives me an output shown at this [link](https://www.dropbox.com/s/4dmmeu91v0o8sfg/spillover_regression_table.doc?dl=0).

I am wondering why the `custom.gof.rows` values do not appear and the names of my mapped `custom.coef.map` appear different from the way I have mapped them.

Also, is there a way to automatically fit the output to the page or set that the output doc is in landscape mode?

**Comment by leifeld** [comment]
Hi Jason! Thanks for reporting this. Can you provide a self-contained minimal example to reproduce the problem? Also, the link you provided does not seem to work currently. Thanks!

**Comment by jasonjb82** [comment]
Hi Philip, thanks for your reply. Apologies on the link. I am also unsure how to produce a minimal example using the `bife` model output that I have but I am using one from an example dataset below.

```
library(nlme)
model.1 <- lme(distance ~ age, data = Orthodont, random = ~ 1)
model.2 <- lme(distance ~ age + Sex, data = Orthodont, random = ~ 1)

map <- list("SexFemale" = "Certified share of group",
            "age" = NA)

screenreg(list(model.1, model.2), 
        custom.gof.rows = list("Year Fixed Effects" = c("Yes","Yes"),"Management Unit Fixed Effects" = c(1:2)),
        custom.model.names = c("Deforestation","Deforestation"),
        digits =5,caption="Spillovers",caption.above=TRUE,
        custom.coef.map = map,
        custom.note = "%stars. t statistics in parentheses")
```

Which comes out like this:

```
=============================================================
                               Deforestation   Deforestation 
-------------------------------------------------------------
Certified share of group                         -2.32102 ** 
                                                 (0.76142)   
age                               0.66019 ***     0.66019 ***
                                 (0.06161)       (0.06161)   
-------------------------------------------------------------
Year Fixed Effects                                           
Management Unit Fixed Effects                                
AIC                             455.00252       447.51251    
BIC                             465.65627       460.78231    
Log Likelihood                 -223.50126      -218.75625    
Num. obs.                       108             108          
Num. groups: Subject             27              27          
=============================================================
*** p < 0.001; ** p < 0.01; * p < 0.05. t statistics in parentheses
```

I have managed to work out the `custom.coef.map` by removing the quotes around the NA so that isn't an issue for me any longer. However, I am still not getting the gof values using `custom.gof.rows` for each model (`Year Fixed Effects`, `Management Unit Fixed effects`) 

Another issue I am trying to figure out is how to omit variables that are very similar using `omit.coef.` For example i have 2 variables called `factor(kh_class)0:g_cert_shr` and another called `factor(kh_class)0`. How do I exclude just  `factor(kh_class)0` ?

Also, is it possible to insert a row of values between `Certified share of group` and `age `in my example below? Or is it only possible to have them inserted at the bottom part of the table?
```
=============================================================
                               Deforestation   Deforestation 
-------------------------------------------------------------
Certified share of group                         -2.32102 ** 
                                                 (0.76142)   
New row                                          -0.66025 ** 
                                                 (0.00056)
age                               0.66019 ***     0.66019 ***
                                 (0.06161)       (0.06161)   
-------------------------------------------------------------
```
Thank you!
--



--

**Comment by leifeld** [comment]
There is apparently a bug in the `custom.gof.rows` argument. I have made a lot of changes recently, so I probably broke the functionality accidentally. I'll look into this over the weekend. Sorry about that.

With regard to the second problem, you could try something like this: `omit.coef = "factor(kh_class)0$"`. The `$` at the end means match only instances where nothing else follows after the keyword. I can't test it properly without a minimal example, unfortunately, so no guarantees.

It's currently not possible to insert rows in other positions than the GOF block. But if you'd like to take a stab at it, I'd be happy to consider a pull request.

**Comment by leifeld** [comment]
OK, I think I have fixed it. Can you try again with the latest build and let me know if it works and if you have any other related questions?

**Comment by jasonjb82** [comment]
Thanks @leifeld, it works now.
