### ISSUE TITLE
Rename, reorder, and omit variables more efficiently for many model terms

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#13]
Comment by user [dan](https://r-forge.r-project.org/users/dan/) on R-Forge:

Dear Philip,

I often have models with hundreds of coefficients (many of which get thrown away). I was about to write my own functions for renaming, reordering, and omitting variables before passing them to ``texreg`` when I discovered this blog post that already contains code to do it:
http://conjugateprior.org/2013/10/call-them-what-you-will/

It has a really nice interface: just define a "name map" that gives the order and new names of any variables you want and omits anything you want to omit, and it automatically builds the parameters to pass to ``custom.coef.names``, ``reorder.coef``, and ``omit.coef``. (And it's robust to including variables that aren't in the model, so it's reusable throughout a project with different models.) This is unbelievably useful and would make a great addition to ``texreg`` itself.

I didn't see ``texreg`` on github or I'd send a pull request. I'm honestly not sure how to submit a patch through R-forge, but the code is already there in the link above, so it shouldn't be hard to add.

This also satisfies a feature request from a couple years ago in this thread:
https://r-forge.r-project.org/forum/forum.php?thread_id=28268&forum_id=4325&group_id=1420

Thanks for your work on ``texreg``!

Best,
Dan

**Comment by vincentarelbundock** [comment]
closed by https://github.com/leifeld/texreg/pull/30
