### ISSUE TITLE
create table for a multivariate model (different dependent variables)

### ISSUE THREAD

**Issue by sdaza** [leifeld/texreg#133]
Hello, 

I am trying to create a table for a multivariate model (different dependent variables). 

- Model m has coefficients like: dep1_var1, dep2_var1, dep3_var1
- I would like to organize coefficients by column and dependent variable
- I would need to apply texreg  to the same model (`texreg(list(m, m, m)`), but filtering and renaming only the dep1 coefficients for the first column, dep2 for the second, and so on. 

Any ideas or suggestions on how to do this? It looks like I cannot filter coefficients separately for each model (the same model in this case) from the the list. 

Thanks!

**Comment by czucca** [comment]
Hi there, 

have you tried with `omit.coef`, omitting the coefficients you don't need, or `custom.coef.map`, omitting the coefficients you don't need + renaming the coefficients you want to keep in the same way over columns so they are printed in the same row?

Hope this helps, 
Claudia

**Comment by sdaza** [comment]
Thanks @czucca. The problem is that I need to remove and rename coeff using the same model in order to get them in the same table:

|      | dep1 | dep2 | dep3 | dep4 |
|------|------|------|------|------|
| var1 |      |      |      |      |
| var2 |      |      |      |      |
| var3 |      |      |      |      |

if I get just one multivariate model (m), and these coefficients dep1_var1, dep2_var1, dep3_var1, dep4_var1, etc..., how I could create the table above omit.coeff or custom.coef.map:

```
custom.coef.map = list(dep1_var1 = 'var1', 
                                        dep1_var2 = 'var2', 
                                        dep1_var3 = 'var3')

texreg(m, custom.coef.map = custom.coef.map)
```

The code above creates only one table and column. I would need to create one table with 4 columns.

`texreg(list(m, m, m, m), custom.coef.map = custom.coef.map)`

I wouldn't know how to select coefficient by model.

Thanks!

**Comment by czucca** [comment]
please give me a reproducible example

**Comment by sdaza** [comment]
Let's assume this is a multivariate model (several dependent variables):

# let's assume this model is multivariate (several dependent variables)

```
dep = runif(30)
dep1_var1 = runif(30)
dep1_var2 = runif(30)
dep2_var1 = runif(30)
dep2_var2 = runif(30)

m = lm(dep ~ dep1_var1 + dep1_var2 + dep2_var1 + dep2_var2 - 1)
custom.coef.map = list(
                       dep1_var1 = 'var1',
                       dep1_var2 = 'var2',
                       dep2_var1 = 'var1',
                       dep2_var2 = 'var2')

screenreg(list(m, m),
  custom.model.names = c('dep1', 'dep2'), 
  custom.coef.map = custom.coef.map)
```

**Comment by czucca** [comment]
1) are you actually using `lm`? I'm asking because I need to see how `texreg` extracts the output
2) if you want to remove coefficients just don't write them in `custom.coef.map` and rename the required ones. Which is what I suggested in the first place. E.g.

```
custom.coef.map = list(
                       dep1_var1 = 'var1',
                       dep1_var2 = 'var2',
                       dep2_var2 = 'var2')
```
3) from what you wrote before I thought the package you are using is computing the same model with several dep vars and giving you the output and you need to extract only one output per time calling the model. Such as m[[dep1]], m[[dep2]]. That's why I asked reproducible code. if this is not the case: a)I'a  not understanding you correctly, b) my first suggestion work, c) I might have no idea :)

**Comment by sdaza** [comment]
Thanks!

1. I am not using `lm`, the example I wrote is just to make the examples simpler. The structure of the coefficients I get is the same: `dep_var`.
2. I am using a `brms` model. For instance, [here](https://cran.r-project.org/web/packages/brms/vignettes/brms_multivariate.html). The structure is the same. 
3. I am using my own (extract function)(https://github.com/sdaza/income-mobility-le-gap/blob/master/src/utils/extract_stan.R)
4. The key issue here is how to combine columns when the coefficient name is changing.

**Comment by czucca** [comment]
so the problem with `custom.coef.map` is that it is generating `var1 `and `va1_1` in the output instead of putting them together. Right?

**Comment by sdaza** [comment]
the problem with `custom.coef.map` is that it is fixed by model. If I could use a different custom.coef.map per model like this: 

```
map1 = list(dep1_var1 = 'var1',
                   dep1_var2 = 'var2')

map2 =  list(dep2_var1 = 'var1',
                    dep2_var2 = 'var2')

# same model used multiple times
screenreg(list(m, m), 
  custom.model.names = c('dep1', 'dep2'), 
  custom.coef.map = c(map1, map2))
```

It will work.

**Comment by czucca** [comment]
I think that the easier way to go since you already have your own extract function is: 
- take the output of the model and put it a dataframe
- fix the names of the coefs as you need
- make the extract function take data from the data frame and save it in a variable
- pass to texreg the variable

**Comment by sdaza** [comment]
Thanks!

**Comment by leifeld** [comment]
Glad you found a solution. Let me add a few things:
1. `brmsfit` models were recently added in commits 3f1608d4957bb89e975a28ca750854f24fcb680f and 867097566d2f2b6fb850414762f9a95542d17a79. If you find anything there that needs improvement, please comment here.
2. I would just use the `extract` function to save the model into three objects, then manipulate the slots for these objects as needed, and finally hand them over to `screenreg` as a list. Not data frame needed.

**Comment by sdaza** [comment]
Thanks, @leifeld. That's what exactly I did:

https://github.com/sdaza/reentry-chile/blob/master/reports/social_integration/src/utils.R
