### ISSUE TITLE
Error running screenreg or htmlreg of bife model outputs

### ISSUE THREAD

**Issue by jasonjb82** [leifeld/texreg#138]
My previous bife model outputs worked properly when creating tables but when I run screenreg / htmlreg now, I get this error

```
Error in extract(l[[i]], ...) : 
  Neither texreg nor broom supports models of class list.
```
The code I am using is basically this 
```
# Create regression table
screenreg(list(cert.bife,pcc.bife,pcckh.bife,gc.bife,gckh.bife,all.bife,allkh.bife),
          custom.coef.map = map)

```

I also notice then my previous code to extract the bife model outputs as below
`cert.bife = extract(cert_ape, include.nobs = TRUE,include.events=TRUE,include.aic=FALSE,include.bic=FALSE,include.loglik=FALSE)`

now gives me this error 
```
Error in extract(cert_ape, include.aic = FALSE, include.bic = FALSE) : 
  incorrect number of dimensions
```
So i have used this instead
`cert.bife = extract(cert_ape)`
but not sure if it works the same way

**Comment by leifeld** [comment]
Apparently the definition of `bife` objects changed. I have made some changes to the code base to reflect these changes and will push them into the master branch shortly. I have also added a unit test, which should flag up any future problems of this kind with `bife` models. That said, the errors I got were different from the errors you are describing, so I'm not sure what to make of that. Without a minimal reproducible example, I cannot look into this further. But if you decide to check out the new version and there are still any problems, please feel free to reopen this issue.
