### ISSUE TITLE
Indentation for groups with latex output

### ISSUE THREAD

**Issue by pkollenda** [leifeld/texreg#141]
I had used the CRAN texreg version for the longest time and have recently switched to the main github version. Since switching, variable labels that are grouped are not indented anymore in LaTex output. Previously the indentation was done with \quad , but this disappeared.

Anything I am doing wrong or is this a bug? Screenreg still gives indented output.

**Comment by leifeld** [comment]
This must have disappeared during a rewrite last year. I have now added it back in. Thanks for the bug report!
