### ISSUE TITLE
Wrong dcolumn width when using custom.gof.rows

### ISSUE THREAD

**Issue by davben** [leifeld/texreg#142]
I'm using the current `texreg` version from Github and have run into an issue of `dcolumns` that are unnecessarily wide. This is related to #119 but for the special case of having additional rows added to a table using the `custom.gof.rows` argument as explained in #10.

As far as I could retrace this behaviour, the reason seems to be this: The `output.matrix` being generated by `texreg::matrixreg()` already puts elements from the list provided to `custom.gof.rows` inside `\multicolumn`-calls (if they are strings). These characters are then included in the count when `texreg:::compute.width()` determines the required space left of the separator.

Here's a short example:

    ctl <- c(4.17, 5.58, 5.18, 6.11, 4.50, 4.61, 5.17, 4.53, 5.33, 5.14)
    trt <- c(4.81, 4.17, 4.41, 3.59, 5.87, 3.83, 6.03, 4.89, 4.32, 4.69)
    group <- gl(2, 10, 20, labels = c("Ctl", "Trt"))
    weight <- c(ctl, trt)

    m1 <- lm(weight ~ group)
    m2 <- lm(weight ~ group - 1)

    texreg::texreg(list(m1, m2), dcolumn = TRUE)

    texreg::texreg(list(m1, m2), dcolumn = TRUE,
                   custom.gof.rows = list("Year FE" = c("no", "yes")))

The two column specifications are
    `\begin{tabular}{l D{.}{.}{2.5} D{.}{.}{2.5}}`
and
    `\begin{tabular}{l D{.}{.}{22.5} D{.}{.}{23.5}}`
which reflect the additional characters stemming from `\multicolumn{1}{c}{no}` and `\multicolumn{1}{c}{yes}`, respectively.

Any idea on how to work around this? Should `compute.width()` ignore LaTeX commands? In any case, thank you so much for this incredibly useful and versatile package!

**Comment by leifeld** [comment]
I seem to remember I fixed this problem a while ago. Probably in the `roxygenize-extract` branch. Can you check if it works better with that version? Thanks.

**Comment by davben** [comment]
Thanks for your quick reply!

Unfortunately, the `roxygenize-extract` branch has the same issue. 

Do you remember how you approached a potential solution? Using some regex in `compute.width()`?

**Comment by leifeld** [comment]
I have fixed the problem. Here is what happens now:

#### Case 1: use of `dcolumn` with text in `custom.gof.rows`:
``` r
texreg(list(m1, m2),
       dcolumn = TRUE,
       custom.gof.rows = list("Year FE" = c("no", "yes")))
```
This should now correctly compute the column width as `2.5` for both columns, i.e., the \multicolumn` entries are not taken into account when the column width is calculated.

#### Case 2: use of text in `custom.gof.rows` without `dcolumn`:
``` r
texreg(list(m1, m2),
       dcolumn = FALSE,
       custom.gof.rows = list("Year FE" = c("no", "yes")))
```
No width computation necessary, but the text is now correctly printed without dollar signs around it, so it is no longer interpreted as a number.

#### Case 3: use of numbers in `custom.gof.rows` with `dcolumn`:
``` r
texreg(list(m1, m2),
       dcolumn = TRUE,
       custom.gof.rows = list("Year FE" = c(123456, 123)))
```
In this case, the numbers are decimal-aligned (i.e., not surrounded by `multicolumn`), and the width is correctly calculated to be `6.5` and `3.5`, respectively.
