### ISSUE TITLE
Reporting AIC and BIC for `lm` models?

### ISSUE THREAD

**Issue by jdnguyenswin** [leifeld/texreg#143]
Is there any way to report AIC and BIC goodness of fit statistics for `lm` models?

For example:

```
library(texreg)
mtcars
model1 <- lm(mpg ~ disp, data = mtcars)
model2 <- lm(mpg ~ disp + hp, data = mtcars)
screenreg(list(model1, model2))
```
Gives me this:

```
=================================
             Model 1    Model 2  
---------------------------------
(Intercept)  29.60 ***  30.74 ***
             (1.23)     (1.33)   
disp         -0.04 ***  -0.03 ***
             (0.00)     (0.01)   
hp                      -0.02    
                        (0.01)   
---------------------------------
R^2           0.72       0.75    
Adj. R^2      0.71       0.73    
Num. obs.    32         32       
RMSE          3.25       3.13    
=================================
*** p < 0.001, ** p < 0.01, * p < 0.05
```
and I'd just like to add AIC, BIC to the stats at the bottom.

**Comment by leifeld** [comment]
AIC and BIC are based on the maximized log likelihood. The `lm` function uses ordinary least squares and not maximum likelihood estimation. Hence there is no likelihood and no AIC or BIC. However, to get AIC and BIC, you can estimate the model using the `glm` function and a Gaussian link function, in which case you get AIC and BIC by default.
