### ISSUE TITLE
Part of custom.coef.map CRAN documentation is cut off

### ISSUE THREAD

**Issue by MaxGhenis** [leifeld/texreg#148]
From https://cran.r-project.org/web/packages/texreg/texreg.pdf:
![image](https://user-images.githubusercontent.com/6076111/81215349-104f9380-8f8e-11ea-8724-a2f966f5b3ef.png)

Relevant code:
https://github.com/leifeld/texreg/blob/42108ac12103f23b6769e38bb6cdbfd4745bbe98/R/texreg.R#L693-L695

**Comment by leifeld** [comment]
Thanks. I have checked the current version of the reference manual. There are a few bad boxes, but nothing is cut off at the page limit anymore. To try out the new version, clone the repository to your computer and run `R CMD Rd2pdf texreg` in the parent directory. This will create the PDF for you, at least if you have all the necessary LaTeX etc. tools installed on your computer.
