### ISSUE TITLE
texreg function splits the GOF statistics with binomial and multinomial logit regressions

### ISSUE THREAD

**Issue by SummerTold** [leifeld/texreg#149]
Hello,

I would like to report multiple regressions from different models in a texreg table. I use binomial logistic regressions through the glm function in stats and a multinomial logistic regression with the multinom function from the nnet package.

The sceenreg and htmlreg functions display the gof statistics on the same lines but not texreg function. There are multiple rows for the number of observations and the log likelihood.

### Minimal Working Example
Below is a minimal reproductible example.

```r
# Packages
require(nnet)
require(texreg)

# Data
df <- data.frame(
  X = sample(1:100),
  Y = sample(c("yes", "no", "maybe"), 100, replace = TRUE)
)

# Empty list for regressions
reg <- list()
# Binomial logistic regressions
reg$yes <- glm(Y == "yes" ~ X, family = "binomial", data = df)
reg$no <- glm(Y == "no" ~ X, family = "binomial", data = df)
reg$maybe <- glm(Y == "maybe" ~ X, family = "binomial", data = df)
# Multinomial logistic regression
reg$multi <- multinom(Y ~ X, data = df)

## Display
# screenreg : GOF OK
screenreg(reg)
# htmlreg : GOF OK
htmlreg(reg)
# texreg : GOF NOT OK
texreg(reg)
```
### Session Information

```r
> sessionInfo()
R version 3.6.3 (2020-02-29)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 10 x64 (build 18362)

Matrix products: default

locale:
[1] LC_COLLATE=French_France.1252  LC_CTYPE=French_France.1252    LC_MONETARY=French_France.1252
[4] LC_NUMERIC=C                   LC_TIME=French_France.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] texreg_1.36.23 nnet_7.3-12   

loaded via a namespace (and not attached):
[1] compiler_3.6.3 tools_3.6.3    packrat_0.5.0 
```

**Comment by czucca** [comment]
Thanks, at first sight, there is a problem with `multinom` printing an escape chart in "Log Likelihood" and "Num. obs.", when `glm' doesn't. Which texreg version are you using? the last GitHub update?

We'll look into that, 
C.

**Comment by SummerTold** [comment]
@czucca Indeed, I did not check the GitHub version. It does work with. Thank you.

**Comment by czucca** [comment]
thanks for letting us know that it is solved!
