### ISSUE TITLE
Flexibly select texreg, screenreg, or htmlreg for knitr, depending on knitr options

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#15]
Reported by David Hugh-Jones by e-mail on 24 June 2016:

Hi Philip

For those using knitr and rmarkdown, something like this could be quite helpful. Tell me if you are interested.

```
flexreg <- function(...) {
   of <- opts_knit$get('out.format')
   if (is.null(of)) {
     screenreg(...)
   } else {
     switch(of,
       'latex'  = texreg(...),
       'sweave' = texreg(...),
       'markdown' = texreg(...),
       'html'   = htmlreg(...),
       screenreg(...)
     )
   }
}
```

David

Update 28 June 2016:

Not many users will know the subtle opts_knit option that the code checks. I think it is quite common for r users to be using rmarkdown via rstudio, and to run chunks at the command line (``screenreg`` needed) then knit the whole document. For ordinary tables, knitr::kable does the job but for regressions... Just my thoughts. 
D

**Comment by leifeld** [comment]
It would be great to get other users' opinion on this. Please upvote or add a comment if you think this is useful.

**Comment by phirsch** [comment]
+1

**Comment by SarBearSchwartz** [comment]
I would love this
