### ISSUE TITLE
Overriding coefficients of only one model in a multi-model output

### ISSUE THREAD

**Issue by SnupSnurre** [leifeld/texreg#150]
Hi! 

Thank you for a great package!

I have a multi-model output containing three models: Model 1, Model 2 and Model 3. 

I would like to override the coefficients of only Model 3 and leave Model 1 and 2 as is. Is this possible? 

Using `override.coef`, I have only managed to change the coefficients of all included models?

Once again, thank you for a great package!

**Comment by leifeld** [comment]
It does not work with the `override.coef` argument, but you can save the results of the model you want to manipulate into an intermediate `texreg` object, replace its coefficients, and then hand it over to `screenreg` in lieu of the original model. That should give you the flexibility you require.

**Comment by leifeld** [comment]
See #5 for examples on how to manipulate intermediate `texreg` objects. I'll close this now as there was no further response.
