### ISSUE TITLE
In htmlreg : Add option to remove / pick what to show between AIC, BIC, Log Likelihood, Deviance, Num Obs

### ISSUE THREAD

**Issue by Fablepongiste** [leifeld/texreg#155]
Would be very useful to be able to pick what to show / remove what we want (or all of them). 
Is it something that can be added as an option ?

**Comment by leifeld** [comment]
It's already there. You can use `include.aic = FALSE` etc. It's documented on the help page of the respective extract function, e.g. extract.nlmer.

**Comment by Fablepongiste** [comment]
Thanks !
