### ISSUE TITLE
bypass print method for data frame output?

### ISSUE THREAD

**Issue by gregmacfarlane** [leifeld/texreg#156]
The three output options of tex, screen, and html do a great job of covering almost all use cases. But I'm wondering if there is a way to get the results printed as a table object that I could print with any other package that has handy functionality for some of the requests that you seem to get a lot (#10, #63, etc). Options might be qwraps2, kableExtra, or xtable. Is there a way to bypass the `print` method?

**Comment by leifeld** [comment]
Do you mean something like the `matrixreg` function?

I was under the impression I had fixed #10, but I have now reopened the issue to check if that's actually true.

**Comment by gregmacfarlane** [comment]
That's fabulous, and I can work with that going forward!
