### ISSUE TITLE
custom.model.names not working in plotreg CRAN version

### ISSUE THREAD

**Issue by Periloux** [leifeld/texreg#166]
I have attempted to change the model names using the custom.model.names call. It would work just fine in the past, but there must be something up with the latest update.

Thanks in advance.

**Comment by leifeld** [comment]
Hi Periloux! Can you provide a minimal self-contained example? That should allow me to figure out what is causing this behavior. Thanks a lot in advance! Philip

**Comment by Periloux** [comment]
I have noticed that the custom.model.names function works just fine for screenreg and texreg. However, I believe the problem comes into play when using the new facet layout for plotreg (compared to the simpler output in previous iterations).

__________________________________________


> summary(model1.b<-glm.nb(Total_adopt ~ Protests_first_year
+                       ,data = state))

Call:
glm.nb(formula = Total_adopt ~ Protests_first_year, data = state, 
    init.theta = 4.62227604, link = log)



> plotreg(model1.b,ci.inner = 0.9,#reorder.coef = c(2:7,1),
+         custom.model.name = c("policy diffusion"))
Model: bars denote 0.5 (inner) resp. 0.95 (outer) confidence intervals (computed from standard errors).

[Example.pdf](https://github.com/leifeld/texreg/files/5630162/Example.pdf)

**Comment by czucca** [comment]
Hi Periloux, 

are you trying to rename one coefficient only? Sorry it reads a bit weird in your example. If this is the case, you have to rename all of them in the custom.model.name expression. Plotreg in importing ggplot and that's how ggplot works. Apologies if I'm not understanding the problem correctly yet.

**Comment by Periloux** [comment]
Sorry, no... I meant to circle the "Model 1" in the facet heading before sending the reply. In previous iterations, the model name was free standing. In the latest update, it has been switched to the ggplot output.

**Comment by czucca** [comment]
@Periloux  I see. There is something not working apparently. 
@leifeld If you allow me I can take care of this one.

**Comment by czucca** [comment]
@leifeld  in -GitHub version 1.26.25 it was definitely working since I used it (I still have the plots). Hence, it must have broke down later.

**Comment by leifeld** [comment]
Thanks for providing the example. Sure, please go ahead and fix it! Thanks both!

**Comment by Periloux** [comment]
Thanks for the quick response
