### ISSUE TITLE
fixest support

### ISSUE THREAD

**Issue by johnsonzhj** [leifeld/texreg#169]
Recently, I noticed that the classical package _lfe_ is not available from CRAN. Since the new released package _fixest_ is good for fixed effect and clustered standard error calculation. Is that possible to add a function for _texreg_ so that it could support the output of the fixest package?

**Comment by leifeld** [comment]
Just added to the master branch on GitHub. It will find its way to CRAN in a few weeks or months when enough changes have been made to justify a CRAN update.
