### ISSUE TITLE
Option to omit standard errors

### ISSUE THREAD

**Issue by avsaase** [leifeld/texreg#173]
I have not been able to find this anywhere, but my apologies if I missed something. 

It would be nice to have the option to omit all standard errors from the regression table. My use-case is I am making a table with the output from the `multinom()` function from the `nnet` package. The coefficients are reported as log odds ratios so to print the normal odds ration I manually provide the exponentiated coefficients using the `override.coef` option. But with this transformation, the standard errors cannot be normally interpreted so I'd rather omit them from the table altogether and have just the significance stars.

**Comment by czucca** [comment]
Have you tried to pass to `override.se` a string of empty characters?

**Comment by leifeld** [comment]
See also my answer [here](https://stackoverflow.com/questions/61801728/how-to-include-odds-ratio-in-texreg-table).
