### ISSUE TITLE
avoid partial matching

### ISSUE THREAD

**Issue by helix123** [leifeld/texreg#18]
In some of the `extract.*` functions partial matching is done due to the `$` operator.
This can be checked with setting these options and running the code

```
options(warnPartialMatchAttr   = TRUE,
        warnPartialMatchDollar = TRUE,
        warnPartialMatchArgs   = TRUE)
```

**Comment by leifeld** [comment]
Closed for now. Feel free to open more specific issues or pull requests if you find additional instances of partial matching! Thanks.
