### ISSUE TITLE
Bug: Omitting projected gof for felm function (lfe)

### ISSUE THREAD

**Issue by AndreWal** [leifeld/texreg#191]
Hi,

Omitting the projected gof doesn't seem to work when using felm with texreg.

Reproducible example:
library(texreg)
library(lfe)

x <- c(1:10)

y <- rep(c(2,4,7,-1,2),2)

m <- felm(y~x)

screenreg(m, include.proj.stats = F)

Thanks for this great package!

**Comment by leifeld** [comment]
It seems to work for me. Can you check which version you are using (`packageVersion("texreg")`)? I am using 1.38.6. What is the output you are getting?

**Comment by AndreWal** [comment]
I have been using version 1.37.5; wasn't aware that it isn't the most recent version. texreg() is not longer displaying the projected gof after the update. Apologies for any inconvenience.

**Comment by leifeld** [comment]
No problem! Glad it works!
