### ISSUE TITLE
Good systemfit integration usually, but does not work with `huxtablereg`

### ISSUE THREAD

**Issue by adirlanz** [leifeld/texreg#192]
This package is amazing and has helped immensely.  
The bug that was found here I came across trying to solve another issue, that it is not possible to assign different levels of rounding to different sections of the table and to different types of measures (for example in this case coefficients versus the goodness-of-fit). I actually came to a [good potential solution on stackoverflow](https://stackoverflow.com/questions/71947231/) by using huxtable.   
I put my systemfit object, a Seemingly Unrelated Regressions set of several individual regressions, into `texreg::huxtablereg(l=mySUR, ...)` with my usual settings. Unlike every other function that generates the table, in particular `knitreg`, which is similar and which I have used most, the function is unable to distinguish that there are multiple models present. If I just put in my systemfit SUR  object, it produces a single column listing all of the involved variables, like when calling/printing the object itself without `summary`.  
The calls `texreg::huxtablereg(l = anyBigSUR, ci.force = T, digits = 2, beside = TRUE)` and  
`texreg::knitreg(l = anyBigSUR, ci.force = T, digits = 2, beside = TRUE)` should result in roughly similar objects, obviously in the different resulting formats, but they do not. The only conclusion is the `huxtablereg` is broken. 
  
Thanks to [dash2](https://stackoverflow.com/users/10522567/dash2) for helping to identify this bug. It's discovery is [documented here](https://stackoverflow.com/questions/71947231/is-there-a-reasonable-way-with-texreg-or-similar-in-r-making-html-tables-to-ro/72315732#72315732), and in the comments.  
  
I have not done this before, so I apologize if I am breaking any conventions or norms on these things.

**Comment by leifeld** [comment]
Let me tag @hughjonesd, who also wrote the `huxtablereg` function in `texreg`.

The `huxtablereg` function can be found [here](https://github.com/leifeld/texreg/blob/a80fce751117cc66c38047130da8471ec68068ec/R/texreg.R#L542).

The `extract.systemfit` method returns a list of `texreg` objects rather than a single `texreg` object when `beside = TRUE` is used.

**Comment by hughjonesd** [comment]
OK, here's a minimal example of the bug for reference:

```r
library(systemfit)
library(texreg)
data( "Kmenta" )
eqDemand <- consump ~ price + income
eqSupply <- consump ~ price + farmPrice + trend
system <- list( demand = eqDemand, supply = eqSupply )
fitols <- systemfit( system, data=Kmenta )

screenreg(fitols, beside = TRUE) # works, producing two separate columns
huxtablereg(fitols, beside = TRUE) # doesn't, just produces one column.
```
