### ISSUE TITLE
packages

### ISSUE THREAD

**Issue by radimbohacek** [leifeld/texreg#193]
Hi Philip,
thanks a lot for the package, I would like to ask you to avoid the insertion of \usepackage{booktabs} and \usepackage{dcolumn} at the top of each table in texreg.
I use a small function to enbed the texreg table in a latex top and commands and run it automatically. 
It does not run when usepackages appear inside the document.
Everyone can put these packages into the preamble and keep it there.
Or at least make it optional.
Thanks a lot best
Radim

**Comment by leifeld** [comment]
Hi Radim! You should be able to achieve this using the argument `use.packages = FALSE`.

**Comment by radimbohacek** [comment]
Hi Philip,
oh sorry, I missed that, sorry for that.
This option is not stated when you describe booktabs in the texreg
description, but I guess I am the first one to miss the other one.
Thanks again, best
Radim

**Comment by leifeld** [comment]
No worries. Good luck!
