### ISSUE TITLE
Add reference group option

### ISSUE THREAD

**Issue by victorhartman** [leifeld/texreg#198]
When using categorical variables in linear regression, showing the reference group / category in the result table is essential to understand the results. I have noticed that R itself also does not display these groups in the summary() function. I think it would be really useful if it is added to texreg. Let me give an example.

<img width="241" alt="image" src="https://user-images.githubusercontent.com/6608079/189368981-5a475051-ff5c-4baa-aa60-881db718bb9b.png">

Currently, the 'poorest' category is missing. I would suggest adding it and showing a dash for the coefficients. Like it is in the image above.

My suggestion for the implementation is to look in the at the 'xlevels' list found at `model$xlevels`. Then iterate over this list and add each first item of each vector in the list. For example model$xlevels[[1]][1] would have been the 'poorest' category that I wanted to add. The value of this item in the output could be a \textemdash

I have looked if someone else has this issue, but couldn't find anything. Hopefully a solution could be implemented!

**Comment by leifeld** [comment]
This sounds useful, but the implementation might depend on the respective model and would require revising more than a hundred `extract` methods. Perhaps a solution could be to save the output of `extract` to an object, edit the object and add any coefficient rows, then feed the object into `texreg`. Not sure if that would work, but perhaps worth a try. I will close the issue for now, but feel free to open if you have a better solution.
