### ISSUE TITLE
extract() object with two classes: uses default instead of next method?

### ISSUE THREAD

**Issue by MatthieuStigler** [leifeld/texreg#200]
Hi

Let's assume ones writes a wrapper to a function known to texreg,  resulting into an object with two classes,  `c("unknown", "fixest")`. My assumption was that having no method for `unknown`, extract would use the `fixest`, but it seems instead it is resorting to the `default` method?

Is that intended? If yes, how should I define extract.unknown so that it uses extract.fixest? Pardon my low knowledge of S4, I am having trouble defining `setMethod()` for the new object, as well as trouble with accessing the code of `extract.fixest`. Thanks!

``` r
library(fixest)
suppressPackageStartupMessages(library(texreg))

## define reg and new reg class
reg <- feols(Sepal.Length ~ Sepal.Width + Petal.Length | Species, iris)
reg_new <- reg
class(reg_new) <- c("unknown", class(reg))

## What I want
screenreg(reg, include.rsquared = FALSE, include.adjrs = FALSE)
#> 
#> ==============================
#>                       Model 1 
#> ------------------------------
#> Sepal.Width             0.43  
#>                        (0.16) 
#> Petal.Length            0.78 *
#>                        (0.13) 
#> ------------------------------
#> Num. obs.             150     
#> Num. groups: Species    3     
#> ==============================
#> *** p < 0.001; ** p < 0.01; * p < 0.05

## What I get
screenreg(reg_new, include.rsquared = FALSE, include.adjrs = FALSE)
#> Warning in doTryCatch(return(expr), name, parentenv, handler): texreg used the
#> broom package to extract the following GOF measures, but could not cast them to
#> numeric type: pseudo.r.squared
#> 
#> ==========================
#>                   Model 1 
#> --------------------------
#> Sepal.Width         0.43  
#>                    (0.16) 
#> Petal.Length        0.78 *
#>                    (0.13) 
#> --------------------------
#> R^2                 0.86  
#> Adj. R^2            0.86  
#> within.r.squared    0.64  
#> Sigma               0.31  
#> nobs              150     
#> AIC                79.57  
#> BIC                94.63  
#> Log Likelihood    -34.79  
#> ==========================
#> *** p < 0.001; ** p < 0.01; * p < 0.05
```

<sup>Created on 2023-01-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by leifeld** [comment]
I see three possible ways to achieve this:

1. Figure out if the S4 system allows dispatching methods based on multiple or subsidiary class signatures. Perhaps there are some details [here](https://adv-r.hadley.nz/s4.html), but I don't have enough time to work through this now.
2. The generic `extract` function first screens if it recognises the first class signature and then dispatches the registered `extract` method. If not, it executes the `ANY` method of the generic `extract` function, as defined [here](https://github.com/leifeld/texreg/blob/9bd6a687bd3ffa1b20c74c76f0ac198ea91cab0c/R/extract.R#L612). Currently, this `ANY` signature points to [`extract.broom` ](https://github.com/leifeld/texreg/blob/9bd6a687bd3ffa1b20c74c76f0ac198ea91cab0c/R/extract.R#L536) and attempts to let the `broom` package extract the coefficients etc. If that fails, it stops with an error. One could write an `extract.ANY` function and let it screen the remaining class signatures for a signature it recognises and dispatch the appropriate method. Perhaps using recursion, or perhaps by checking what methods are registered for `extract` so no double book keeping is required. Only if none of the signatures is recognised, one could attempt `extract.broom`.
3. If the class signature you use is always `unknown`, you could write an `extract.unknown` function and register it as a method for the `extract` generic function. The function could screen the remaining class signatures and extract the appropriate information, depending on what signature is found. Something like this was implemented for [`extract.Zelig`](https://github.com/leifeld/texreg/blob/9bd6a687bd3ffa1b20c74c76f0ac198ea91cab0c/R/extract.R#L8851), for example.

Probably the second thing would be the most general solution. I'm fairly busy these days, but if you'd like to do a pull request, I'm happy to review it.

**Comment by MatthieuStigler** [comment]
Thanks Philip for your fast answer!

So I ended up going in my case for case 3, write a small custom setMethod, passing to the next one. And I think method 1 should be the way to go. I am fairly busy too these weeks but if I get time, I'll try to figure it out and send a pull request!

**Comment by leifeld** [comment]
That sounds good, thanks. I'll close this issue for now, but please feel free to reopen it if necessary or create a new issue or PR and reference this one.
