### ISSUE TITLE
texreg::screenreg does work within a for loop

### ISSUE THREAD

**Issue by mrmelchi** [leifeld/texreg#202]
# Performs data analysis to create a macro factor model for FAANG stocks.
# does the necessary data analysis using actual data and statistical models
# and then concludes how to construct your macro factor model. 
# In addition, shows what macro factors are, factor betas for FAANG, and show how factor betas
# change.

library(tidyverse)
library(quantmod)
library(lubridate)
library(dplyr)
library(texreg)

FAANG <- c("META", "AMZN", "AAPL", "NFLX", "GOOGL")
macro <- c("GDPC1", "CPIAUCSL", "DTB3","DGS10","DAAA","DBAA","UNRATE","INDPRO","DCOILWTICO")

for (i in 1:length(macro)) {
  getSymbols(macro[i], src = "FRED")
  data <- as.data.frame(get(macro[i]))
  data$date <- as.POSIXlt(strptime(rownames(data), "%Y-%m-%d"))
  rownames(data) <- NULL
  colnames(data) [1] <- "macro_value"
  data$quarter <- as.yearqtr(data$date)
  data$macro_ticker <- rep(macro[i], dim(data)[1])
  
  data <- data %>%
    mutate(date = ymd(date)) %>%
    group_by(quarter) %>%
    top_n(1, date) %>%
    filter(date >= "1980-01-01", date <= "2019-12-31") %>%
    select(-date)
  
  if (i == 1) {macro_factors <- data} else {macro_factors <- rbind(macro_factors, data)}
  
}

for (i in length(FAANG)) {
  getSymbols(FAANG[i], source = "yahoo", from="1979-12-01", to="2019-12-31", periodicity= "monthly")
  data <- as.data.frame(quarterlyReturn(get(FAANG[i])[,6]))
  data$date <- rownames(data)
  data$ticker <- rep(FAANG[i], dim(data)[1])
  data <- data %>%
  mutate(date = ymd(date)) %>%
  mutate(quarter = as.yearqtr(date)) %>%
  select(-date)

  data_MacroModel <- left_join(macro_factors, data, by="quarter")  %>%
  na.omit() %>%
  spread(key = macro_ticker, value = macro_value)
  
  MacroModel <- lm(quarterly.returns ~  GDPC1+CPIAUCSL+DTB3+DGS10+DAAA+DBAA+UNRATE+INDPRO+DCOILWTICO,
                 data = data_MacroModel, na.action = "na.exclude")
 
  print(texreg::screenreg(MacroModel, custom.model.names = as.character(FAANG[i])))
}

print(texreg::screenreg(MacroModel, custom.model.names = as.character(FAANG[i]))) only print the last loop -> GOOGL

Thnak you in advance.

**Comment by leifeld** [comment]
Try `1:length(FAANG)` instead of `length(FAANG)` when you define iterator `i`.

**Comment by mrmelchi** [comment]
Sorry to bother you. What a silly mistake.

Thank you.

**Comment by leifeld** [comment]
Never mind! Happened to me before.
