### ISSUE TITLE
Bug omitting CI tests with multiple models

### ISSUE THREAD

**Issue by Mv77** [leifeld/texreg#203]
Hi,

I have been trying to use texreg to produce a table with multiple models. I would like to have it present confidence intervals instead of standard errors. Additionally, I do not want it to perform any confidence interval test.

From the documentation, to prevent the tables from reporting any tests, I can use the option `ci.test`:
"...If no star should be printed at all, ci.test = NA can be used. It is possible to provide a single value for all models or a vector with a separate value for each model."

So if I have two models and I don't want to have tests in either I would do `ci.test=c(NA,NA)`. However, this produces the following bug, which I believe comes from the input sanitizers:
```
Error in !is.numeric(ci.test) && !is.null(ci.test) && !is.na(ci.test) : 
  'length = 2' in coercion to 'logical(1)'
```
The conditions evaluate to a vector because `ci.test` is a vector. But then the vector can not be used in an if statement.

Here is a minimal example that reproduces the bug
```
# Generate some example regression models
model1 <- lm(mpg ~ cyl + disp, data = mtcars)
model2 <- lm(mpg ~ cyl + hp, data = mtcars)

# Create the texreg table
screenreg(list(model1, model2),
  custom.model.names = c("Model 1", "Model 2"),
  ci.force = TRUE,
  ci.test = c(NA, NA)
)

```

**Comment by TimothyMerlin** [comment]
Hi

I've encountered the same issue when using `NA` as a single value for the `ci.test` argument across multiple models. I share @Mv77's conclusion regarding the cause of the bug.

Below is my slightly adapted minimal, reproducible example to demonstrate the problem:

```R
# Generate some example regression models
model1 <- lm(mpg ~ cyl + disp, data = mtcars)
model2 <- lm(mpg ~ cyl + hp, data = mtcars)

# Create the texreg table
screenreg(list(model1, model2),
  custom.model.names = c("Model 1", "Model 2"),
  ci.force = TRUE,
  ci.test = NA
)
```

This produces the following bug, which seems to be a sanitizer in `texreg::get_stars_note`:

```R
Error in !is.numeric(ci.test) && !is.null(ci.test) && !is.na(ci.test) : 
  'length = 2' in coercion to 'logical(1)'
````

**Comment by leifeld** [comment]
Thanks, I have fixed the issue and added a unit test. I will submit a new version to CRAN.
