### ISSUE TITLE
Adding a Title Option to the screenreg() Function

### ISSUE THREAD

**Issue by linem7** [leifeld/texreg#204]
Hi Philip,

I am using the `screenreg()` function in my project and I find it incredibly useful. However, I realized that there is no straightforward option to add a title to the generated table. This would be a beneficial feature to have, as it would make the tables more descriptive and easier to understand.

Here's a brief example of what I'm looking for:

```R
screenreg(model, title = "Summary Statistics")
```

Could you please consider adding this feature? Or if there is an existing way to achieve this that I might have missed, I would greatly appreciate your guidance.

Thank you for your time and consideration.

Best regards,
Chaopai Lin

**Comment by leifeld** [comment]
How would this solution work for you? I don't think it's necessary to include this in the table itself.

```r
library("texreg")
ctl <- c(4.17, 5.58, 5.18, 6.11, 4.50, 4.61, 5.17, 4.53, 5.33, 5.14)
trt <- c(4.81, 4.17, 4.41, 3.59, 5.87, 3.83, 6.03, 4.89, 4.32, 4.69)
group <- gl(2, 10, 20, labels = c("Ctl", "Trt"))
weight <- c(ctl, trt)
lm.D9 <- lm(weight ~ group)
lm.D90 <- lm(weight ~ group - 1)
s <- screenreg(list(lm.D9, lm.D90))
cat("\nTable 1: Two models", s)
```
The result looks like this:
```
Table 1: Two models 
=================================
             Model 1    Model 2  
---------------------------------
(Intercept)   5.03 ***           
             (0.22)              
groupTrt     -0.37       4.66 ***
             (0.31)     (0.22)   
groupCtl                 5.03 ***
                        (0.22)   
---------------------------------
R^2           0.07       0.98    
Adj. R^2      0.02       0.98    
Num. obs.    20         20       
=================================
*** p < 0.001; ** p < 0.01; * p < 0.05
```

**Comment by linem7** [comment]
Hi Philip,

The method you suggested for adding title worked like a charm! I have to admit, after seeing your solution, I realized it was quite a layman problem, but I really appreciate you taking the time to explain it to me in detail.

Your patience and willingness to help made a huge difference to me, and I'm super grateful. Thanks again for everything!

Best,
Lin

**Comment by leifeld** [comment]
Of course! I'm happy this solution works for you. Take care!  😀
