### ISSUE TITLE
Converting ASCII Table from screenreg to knitr_kable

### ISSUE THREAD

**Issue by linem7** [leifeld/texreg#207]
Hi,

I would like to know if it is possible to convert an ASCII table created by the `screenreg` function to a `knitr_kable` object. I am encountering an issue where my table is too wide to be properly displayed in an RMarkdown document. I wonder if converting the table into a `knitr_kable` object might better fit the RMarkdown file.

Thanks!
Linem

**Comment by leifeld** [comment]
There is currently no infrastructure to convert to `kable`. But there are other ways to include tables than with `screenreg`. Have you tried the `knitreg` function? There are also ways to limit the width of a table, for example using the `single.row`, `no.margin`, and `scalebox` arguments.

**Comment by linem7** [comment]
Hi Philip,

Thank you so much for your suggestion. I will try it later. Great thanks for your work!

Best,
Lin

**Comment by leifeld** [comment]
I assume this worked and will close the issue for now, but feel free to re-open or open a new ticket.
