### ISSUE TITLE
Filtering Regressions

### ISSUE THREAD

**Issue by alanpaulkwan** [leifeld/texreg#22]
I have a use case where I batch submit regressions and then save the serialized output (rds of the returned value of extract(lm) ). This is much better than stargazer (need to save lm, which carries around residuals) or tidy (cannot be entered into an outreg). 

So, when I need to look through hundreds of robustness checks, I simply call a function that filters regressions on dependent variables and independent variables.  Maybe a strange use case. Wondering if it would have general value to add something like this to the package. The beneficiaries would be anyone who has to run batch analysis they need to store for later review. 

Also, in one set of interactions between client and server, I can only receive textual output. I have had to save a string representation of the list that contains a call to tidy and glance from broom, and then write my own bootleg texreg function. Perhaps it would aid batch analysis as well to have a string representation of an extract object. This might violate S4 principles, so it would require creating something like toString for texreg which could then be parsed and converted back.

**Comment by leifeld** [comment]
Thanks. Can you provide more details to clarify what your functions do and who would benefit from them? Perhaps something to add to the wiki in case people are interested?

**Comment by alanpaulkwan** [comment]
Okay sure, I'll put my functions on the wiki

**Comment by leifeld** [comment]
OK, I just opened it up for the public. Let me know in case it doesn't work.
