### ISSUE TITLE
Allow a user to omit coefficients and rename them

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#24]
Bug report by e-mail from Christopher Gandrud on 17 March 2016:

Hi Philip

I noticed in texreg 1.36.4 that users basically can’t (or can’t easily) omit coefficients and provide custom coefficient names for the remaining coefficients.

This is because in:
```
m <- customnames(m, custom.coef.names)  #rename coefficients
m <- rearrangeMatrix(m)  #resort matrix and conflate duplicate entries
m <- as.data.frame(m)
m <- omitcoef(m, omit.coef)  #remove coefficient rows matching regex
```

`omitcoef` comes after `customnames` have been applied. In the attached file I simply moved the `omitcoef` call before `customnames`. Now I can omit coefficients and rename them.

Best
Christopher

Attached revised version of ``texreg``: [texreg.R](https://github.com/leifeld/texreg/files/634994/texreg.R.txt)

/cc @christophergandrud

**Comment by vincentarelbundock** [comment]
closed by https://github.com/leifeld/texreg/pull/30

**Comment by helix123** [comment]
see my comment to #30
