### ISSUE TITLE
Add support for the tabularx environment in LaTeX

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#25]
Further explanation by Shahram Amini via e-mail on 11 November 2016:

Thank you for replying my email and your help. Sometimes the user wants to stretch out the table to fit the width of the text. This task is accomplished by ``tabularx`` environment. This environment takes all the regular `"l"`,`"r"`, and `"c"` arguments but it has extra column type called `"X"`. When `"X"` is used, the table gets stretched out according to a scale passed to the table. The environment looks like this:

```
\begin{tabularx}{\textwidth}{XXX}

......

\end{tabularx}
```

The same task can be accomplished by ``tabular*`` environment but i did not see a support for that one either.

**Comment by czucca** [comment]
this issue was addressed by the September update.

**Comment by ylelkes** [comment]
was this deprecated? i can't seem to find it in help files.

**Comment by leifeld** [comment]
Doesn't seem to have been fixed, so I have reopened this.

**Comment by czucca** [comment]
I think I made the mistake of thinking it was fixed by the issue #72 (see above), but now I checked again what it is and is merely related. Apologies!!

**Comment by leifeld** [comment]
Hi there. I have now added a new `tabular` argument, which is `TRUE` by default and leaves out the `tabular` environment if set to `FALSE`. This should make `texreg` tables more flexible because it can be combined with `tabular*`, `tabularx` etc. environments.

See also #72.
