### ISSUE TITLE
Add custom multicolumn header

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#3]
Comment from user [an ri](https://r-forge.r-project.org/users/anri/) on R-Forge:

I find myself manually adding a multicolumn-header to the output that indicates that two or more regressions belong to a certain group. For instance, if I have four regression models, I may want the word "Women" to appear above the first two regressions, and "Men" above the last two.

**Comment by leifeld** [comment]
Comment from user [felix_h](https://r-forge.r-project.org/users/felix_h/) (Felix Haass) on R-Forge:

Could you add an option that allows for custom ``\multiline{}`` commands in the table header when using ``dcolumn``? Sometimes one needs to create custom multcolumn headers, e.g. to create a table header which is similar to this one http://i.stack.imgur.com/mSVNQ.png. 
![msvnq](https://cloud.githubusercontent.com/assets/5451293/20845828/c004bf58-b8be-11e6-86fd-a79bf8487cce.png)
This works if I simply add the required Latex code as first ``custom.model.name`` option and wrap the other custom.model.names also in ``multicolumn`` statements. Where this fails, is however, when I also use the ``dcolumn`` option, to get nicely aligned columns. Since the ``dcolumn = T`` option automatically wraps each model name in a ``\multicolumn()`` statement this breaks the code.

My current workaround is that I modified the original if statement in the ``texreg()`` function that checks whether ``dcolumn = T`` and added another condition, namely ``multicolumn = F`` (and also added ``multicolumn = F`` as function argument). The modified code chunk now looks like this:

```
if (dcolumn == TRUE & custom.multicol == FALSE) {
for (i in 2:length(modnames)) {
if (coltypes[i] != "coef") {
tablehead <- paste0(tablehead, " & ", modnames[i])
}
else {
tablehead <- paste0(tablehead, " & \\multicolumn{1}{c}{",
modnames[i], "}")
}
}
}
else {
for (i in 2:length(modnames)) {
tablehead <- paste0(tablehead, " & ", modnames[i])
}
}
```

Thus, if I manually set ``custom.multicol`` to ``TRUE``, I explicitly state that I have included custom ``\multcolumn`` statements in the model names and thus do not require automatic wrapping. Could you add this to the ``texreg`` functionality?

Again thanks for such a great package and keep up the good work!

Best
Felix

**Comment by leifeld** [comment]
Related question on StackOverflow: http://stackoverflow.com/questions/37402445/adding-multicolumns-to-my-texreg-output

**Comment by felixhaass** [comment]
Thanks for migrating all issues to GitHub. If you my workaround from above is adequate, I'm happy to put together a small pull request that incorporates the code above into the main texreg function.

**Comment by leifeld** [comment]
Thanks for your offer. I think it would be better to have a separate code block above the code block you quoted and insert a possible multicolumn header there. I would envision a new argument in the texreg, screenreg, and htmlreg functions that lets the user specify such a header. For example, the user could supply something similar to the `groups` argument: a list of named numeric vectors, such as `header = list("Linear Models" = 1:3, "Poisson models" = 4:5)`. The three functions would then need to figure out the respective ways to typeset this header. In the `texreg` case, this would be done by `multicolumn`s. How does that sound?

**Comment by felixhaass** [comment]
I like the idea of putting the labels in a list of named vectors, b/c it would be much more user friendly. One would probably also need to include an option that enables/disables a `\cline` that separates the multicolumn header from the model names (as in the figure posted above). 

I'm not sure if I'll be able to code something up along those lines, but I'll have a look at it.

**Comment by leifeld** [comment]
I think the `\cmidrule` should be compulsory. I cannot imagine a scenario where a user would not like to have these midrules. Sure, please feel free to make suggestions.

**Comment by eivindhammers** [comment]
Would something like this work? 
It might interfere with some of the other options, but it does the trick for my usage, and might provide a starting point. `col.groups` is specified as suggested above, i.e. `= list("Linear Models" = 1:3, "Poisson models" = 4:5)`, and `\cmidrule` is compulsory. I also check
```
 # Check that col.groups is a list
  if (!is.null(col.groups) & !is.list(col.groups)) {
    stop("col.groups must be a list")
  }
```

It might need another test to verify that the list covers all models in `l`.

It's something I wrote together very quickly last night, but it works.

**Comment by AndreWal** [comment]
Any updates on the issue?

**Comment by powerguo** [comment]
Was this feature ever implemented? Seems like @eivindhammers wrote the preliminary code for it but just wanted to see if this was ever implemented. Thanks!

**Comment by czucca** [comment]
@powerguo  no, it wasn't, but I'm working on it at the moment

**Comment by mschnetzer** [comment]
This would be a great (and important) feature. May I ask if there has been any progress on this issue since the last response here? Thanks!

**Comment by leifeld** [comment]
Hi Everyone,

Good news! I have implemented this feature in `texreg`, `screenreg`, `htmlreg`, and `knitreg` now. See commits 067bb75d33ae6a68469a328b8527331135b9f91e, a3cca5435055b690f4817f3241d9aefb295357b8, 6126079540bbb515742e5c8bf838584072c92f1c, and 2b883b20dbef6f2ad47cb25be86171b9be13ab71. The new argument is called `custom.header` and accepts a named list of integer vectors. It was really a major coding effort, primarily because it interfered with so many other arguments, in particular `custom.columns`.

Here is an example, in which you can see that the argument automatically corrects for gaps in the custom headers (e.g., Model 3 does not have a header) and prior (column "first") or intermittent (column "second) custom columns:

``` r
library("texreg")
data("iris")
model1 <- lm(Sepal.Width ~ Petal.Width, data = iris)
screenreg(list(model1, model1, model1, model1, model1),
          custom.header = list("a to b" = 1:2, "d to e" = 4:5),
          custom.columns = list("first" = c("one", "two"),
                                "second" = c("three", "four")),
          custom.col.pos = c(1, 6))
```
This is the output:
```
======================================================================================
                            a to b                                  d to e            
                    ----------------------              ------------------------------
first               Model 1     Model 2     Model 3     Model 4     second  Model 5   
--------------------------------------------------------------------------------------
one    (Intercept)    3.31 ***    3.31 ***    3.31 ***    3.31 ***  three     3.31 ***
                     (0.06)      (0.06)      (0.06)      (0.06)              (0.06)   
two    Petal.Width   -0.21 ***   -0.21 ***   -0.21 ***   -0.21 ***  four     -0.21 ***
                     (0.04)      (0.04)      (0.04)      (0.04)              (0.04)   
--------------------------------------------------------------------------------------
       R^2            0.13        0.13        0.13        0.13                0.13    
       Adj. R^2       0.13        0.13        0.13        0.13                0.13    
       Num. obs.    150         150         150         150                 150       
======================================================================================
*** p < 0.001; ** p < 0.01; * p < 0.05
```

The functionality in the `texreg` function is quite similar. It uses `\cline` for the lines or `\cmidrule` if the `booktabs` argument is also used. It can deal with `longtable`, `sidewaystable`, `siunitx`, and `dcolumn` as well.

The `htmlreg` function uses `colspan` attributes to achieve the same thing, so the layout is consistent between the three functions. To achieve this, I had to redefine most of the CSS style sheets. I also updated the HTML code to HTML5 and fixed a few glitches.

**Comment by eborbath** [comment]
Hi! Related to this, I was wondering is there a way to have multiline model names, in the way suggested here: https://stackoverflow.com/questions/55782458/how-to-get-multiline-model-names-in-screenreg-and-texreg

**Comment by Eyayaw** [comment]
Hi there, 
Does texreg currently support adding one more header on top? 
For example, 

```r 
texreg(list(mod1, mod2),
custom.header = setNames(list(1:2, 1, 2),
c("Dependent variable: $\\Delta\\ln(P)$ 2008-2019", "All homes", "Single-family homes")
  ), ...
  )
  ```
  so that the first label can go on top. 
Thank you.

**Comment by leifeld** [comment]
Unfortunately just two levels at this point, the model name for each column and the custom header, which can span multiple columns. It may be useful to accommodate additional descriptions in the model name, such as `Single-family homes, 2008--2019`, and/or change the custom headers to be less specific.
