### ISSUE TITLE
Add notes over multiple lines at the end of a table

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#4]
Comment from user [an ri](https://r-forge.r-project.org/users/anri/) on R-Forge:

I find myself manually adding a custom footnote after the tabular environment. The built in function custom.note puts the note into a multicolumn environment, but my annotations are often long, and the table proportions get distorted if I put it into this environment. So I add a custom note below the tabular environment using "\footnotesize". I imagine many other people do so as well.

**Comment by leifeld** [comment]
See also this question on StackOverflow: http://stackoverflow.com/questions/30902906/wrapping-custom-notes-in-texreg-output

**Comment by MichaelChirico** [comment]
Adding my note to you over e-mail:

I'm not familiar enough with LaTeX to know how we might do so automatically, but if we add an argument like `custom.note.wrap`, we could change:

```
else {
        note <- paste0("\\multicolumn{", length(models) + 1, 
            "}{l}{\\", notesize, "{", custom.note, "}}")
        note <- gsub("%stars", snote, note, perl = TRUE)
    }
```

to:

```
if (custom.note.wrap){
  note.split <- character(ceiling(nchar(custom.note)/custom.note.wrap))
  notex <- custom.note
  for (ii in 1:length(note.split)){
    note.split[ii] <- regmatches(notex,regexpr(
      paste0(".{1,", custom.note.wrap, "}(\\s|$)"), notex))
    note<-paste0(if (ii==1) "" else paste0(note," \\ \\n"),
                 "\\multicolumn{", length(models) + 1, 
                 "}{l}{\\", notesize, "{", note.split[ii], "}}")
    notex <- substr(notex, nchar(note.split[ii])+1, nchar(notex))
  }
  note <- gsub("%stars", snote, note, perl=TRUE)
}else{
  note <- paste0("\\multicolumn{", length(models) + 1, 
                 "}{l}{\\", notesize, "{", custom.note, "}}")
  note <- gsub("%stars", snote, note, perl = TRUE)
}

The regex serves to split the string into substrings of length at most `custom.note.wrap` which end in a space, which we then append to the note as a separate multicolumn.

Would be great to see something like this in the official version!

A more parsimonious version takes advantage of the existing `strwrap` function (inspired by [this](http://stackoverflow.com/questions/2351744/insert-line-breaks-in-long-string-word-wrap)):

```
if (custom.note.wrap){
  note<-paste(paste0("\\multicolumn{", length(models)+1L,"}{l}{\\", notesize, "{",
                     strwrap(custom.note, width=custom.note.wrap), "}}"),
              collapse = " \\ \n")
```

**Comment by leifeld** [comment]
Thanks everybody! So we've got three different ways to do it:

1. add a `minipage` or something like that below the `tabular` environment (an ri).
2. add a `multicolumn` with `p{.9\linewidth}` designation (@sdaza).
3. split the note string into multiple components and add a `multicolumn` line for each of them separately (@MichaelChirico).

Which solution is supposed to work best? I am inclined to say number 2. But I'd welcome other views.

**Comment by leifeld** [comment]
Related question on StackOverflow: http://stackoverflow.com/questions/32644498/multiple-lm-texreg-export-with-second-note-line

Here, the user would like to have manual line breaks rather than automatic word wrapping.

**Comment by MichaelChirico** [comment]
I think @sdaza's approach is bound to be most robust. Sounds like a clearly superior version of my initial idea using `strwrap`, which is very ad-hoc. Better to let TeX do the automated line-wrapping itself.

Perhaps just add an option to change .9 to the user's preference?

**Comment by leifeld** [comment]
If we use that solution, the best way is to subtract the cell margin on the left and right, rather than replacing the line width of 1.0 by 0.9: `p{\dimexpr\linewidth-2\tabcolsep}` (see a [related StackOverflow post here](http://tex.stackexchange.com/questions/62710/tabular-with-p-type-columns-to-fill-page-width)).

However, that stretches the whole table to line width, even if it is actually shorter. Here is an example:

```
\documentclass[a4paper,10pt]{article}
\usepackage[utf8]{inputenc}

\title{}
\author{}

\begin{document}

\maketitle

\begin{table}
\begin{center}
\begin{tabular}{l c c }
\hline
 & Model 1 & Model 2 \\
\hline
(Intercept) & $5.03^{***}$ &              \\
            & $(0.22)$     &              \\
groupTrt    & $-0.37$      & $4.66^{***}$ \\
            & $(0.31)$     & $(0.22)$     \\
groupCtl    &              & $5.03^{***}$ \\
            &              & $(0.22)$     \\
\hline
R$^2$       & 0.07         & 0.98         \\
Adj. R$^2$  & 0.02         & 0.98         \\
Num. obs.   & 20           & 20           \\
RMSE        & 0.70         & 0.70         \\
\hline
\multicolumn{3}{p{\dimexpr\linewidth-2\tabcolsep}}{\scriptsize{$^{***}p<0.001$, $^{**}p<0.01$, $^*p<0.05$}}
\end{tabular}
\caption{Statistical models}
\label{table:coefficients}
\end{center}
\end{table}

\end{document}
```
And here is the PDF output: [test2.pdf](https://github.com/leifeld/texreg/files/629404/test2.pdf)

How would we deal with that? Just letting the user figure out a width that still works seems like a kind of hackish solution to me...

/cc @sdaza

**Comment by MichaelChirico** [comment]
right... I guess that means maybe trying to have texreg track the width of
the table.

here's another SO question with slightly different answers:

http://tex.stackexchange.com/q/99326/29219

**Comment by leifeld** [comment]
I think I have solved the problem by adding support for the `threeparttable` and `threeparttablex` LaTeX packages. See #146. This permits wrapping long notes over multiple lines and using line breaks in custom notes.
