### ISSUE TITLE
texreg with the table command.  Rotating the title.

### ISSUE THREAD

**Issue by skanskan** [leifeld/texreg#49]
If I try to get an output from the table command with texreg I get an error

> Error in (function (classes, fdef, mtable)  : 
>   unable to find an inherited method for function ‘extract’ for signature ‘"table"’
> 

`texreg(table(c(2,5,5,5,5,7,7,7,7,NA),c(1,5,2,2,2,2,7,7,NA,NA)))`

How can I get it?
I would like to get the left title rotated, as in this picture:

![btngq](https://cloud.githubusercontent.com/assets/4120283/24590550/3eeaaa3c-17ef-11e7-83f2-b71f78c8ca44.jpg)

**Comment by leifeld** [comment]
The `texreg` package is for regression tables, not for general-purpose tables. For tables like the one you included in your question, you may want to look at the `xtable` package.

**Comment by skanskan** [comment]
OK, thanks, I knew it, but some things are difficult to do with it.
