### ISSUE TITLE
Show p-values as numbers in output

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#5]
Comment by user [Kevin Tappe](https://r-forge.r-project.org/users/kev/) on R-Forge:

I looked around a while for an option to print SE and p values in the table (in separate rows, preferably). It seems like, it is not possible to print the p values at all (other than by indicating significance by stars or by doing some dirty substitution tricks to substitute SEs for p values)?

Would be nice to have an option for that. (stargazer has the report option, e.g. report = c*sp to print coefficients (starred), SE, and p values).

**Comment by alanpaulkwan** [comment]
Similarly, I think it would be nice if one were able to show t-stats. I prefer SEs, but many are used to reporting t-stats.

**Comment by leifeld** [comment]
@alanpaulkwan Thanks for the suggestion. I guess the t-stats suggestion is highly model-dependent because some models have t-stats while most don't. One would probably have to add a t-stats slot to the `texreg` class definition, which is not used by most models. Then each `extract` method where this is applicable could have their own argument for including t-stats instead of SEs. However, to do justice to other models, one would have to come up with similar slots for z-scores and other information. I'm a bit skeptical because adding more and more slots to `texreg` objects is not exactly parsimonious.

**Comment by alanpaulkwan** [comment]
Understood. My field (finance) uses t-stats more often (it sticks out when
they don't, but not necessarily in a bad way), but 5 minutes of empiricism
suggests mainstream economics uses standard errors. I could be wildly off.

How about a simple option to do coef/se?

**Comment by alanpaulkwan** [comment]
Although perhaps a band-aid is not elegant, it also saves the effort of
redefining the extract functions for a wide class of models.

**Comment by leifeld** [comment]
I think I would like a general solution like the one suggested by Kevin at the end of his comment. It would be great if the user could decide which and how many elements (coefficients, SEs, CIs, p-values, significance stars) should be listed and in which order and with which brackets (if applicable). But that would be a major change, and I don't have time to do this right now. It would also affect other arguments, such as `single.row`. If anyone wants to go for it, please feel free to submit a pull request, and I'll consider it.

**Comment by leifeld** [comment]
@alanpaulkwan Have you considered using the `override.se` argument to replace SEs by t-stats? The suggestion in my previous comment would additionally allow you to change the style of the brackets, but inserting t-stats instead of SEs should be possible right now -- just not automatically.

**Comment by lingchuding** [comment]
@alanpaulkwan Hi, I am also attempting to obtain the p values of t-statistics automatically when using texreg. Have you found any way to realize it? Hope to get suggestions from you. Thanks!

**Comment by martincoin** [comment]
# I have 6 models in total. I named them m1:m6
# trick the code to think t-stats are SE. then it will report t-stats. 
# overrise.se = t-stats. 
       , override.se=list(summary(m1)$coef[,3],
                            summary(m2)$coef[,3],
                            summary(m3)$coef[,3],
                            summary(m4)$coef[,3],
                            summary(m5)$coef[,3],
                            summary(m6)$coef[,3]   )

**Comment by VeroBordeaux** [comment]
Thank you @leifeld for this package very usefull. It's true that in some fields we need t-stat to publish results instead of se. 
If it's not possible automatically, perhaps we should do something semi-automatically with override.se et override.pval. I'm a newbee in R but can we get an expression that works every time to take all the $coef[,3] for all the list of model given in l= of the function htmlreg. If it is possible we should put this every time in order to resolve the problem for all regressions we will have to do for our types of review. it would be perfect for me. 
I like also the the possibility to put all in one line and to have the option of bold in automatic. I don't want stargazer for this reason.

**Comment by leifeld** [comment]
Hi Everyone! This thread was opened a few years ago, and there have been many changes in the meantime that have made `texreg` much more complex than before with regard to its arguments and customizability. Given these developments, having arbitrary additional values and parentheses as suggested in my earlier comment seems like a very hard thing to implement if I want to take into account all those arguments and exceptions.

As a consequence, having a tweak to `texreg` like adding a `tstats.to.se` or a `pval.to.se` argument or perhaps an `se.type` argument with values `se`, `tstats`, and `pval` may seem more realistic. Then coef/se or pval could be reported in parentheses instead of the SE. Is this something that people would find useful? If so, please comment here.

Alternatively, you may just want to go via an intermediate `texreg` object, which is also reasonably easy to accomplish, like in the following example. The application is taken from the `lm` help page:

``` r
library("texreg")

ctl <- c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14)
trt <- c(4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69)
group <- gl(2, 10, 20, labels = c("Ctl","Trt"))
weight <- c(ctl, trt)
lm.D9 <- lm(weight ~ group)

tr <- extract(lm.D9)
tr@se <- tr@coef / tr@se
tr@pvalues <- numeric()
screenreg(list(lm.D9, tr), custom.model.names = c("Original", "t-stats"))
```
The output looks like this:
```
===============================
             Original   t-stats
-------------------------------
(Intercept)   5.03 ***    5.03 
             (0.22)     (22.85)
groupTrt     -0.37       -0.37 
             (0.31)     (-1.19)
-------------------------------
R^2           0.07        0.07 
Adj. R^2      0.02        0.02 
Num. obs.    20          20    
===============================
*** p < 0.001; ** p < 0.01; * p < 0.05
```
You can of course still show the p-values if you want, highlight significant coefficients in bold, use `single.row = TRUE` to display coefficient and t-statistics in the same row etc.

Would this solution work for folks here, or is it really necessary to have a separate argument for these things? Thanks for your feedback!

**Comment by nfultz** [comment]
Thanks, the workaround you provided of manually editing the object is good enough, for me, for now. My current client is targeting a journal that wants `$beta ($p.val) $stars` format, so it's easy enough to modify your workaround and call it good. 

`tstats.to.se=TRUE` seems too narrow and somewhat confusing when you read it out loud, and `se.type='pval'` would be confusing at first glance also. 

If you were going to make this configurable, I would recommend a more general refactor of letting the user pass in a format string, eg `cellfmt='%d (%d) %s'`, or some other description what they want, rather than adding a feature that is pretty specific and could easily become tech-debt long term. 

If there were a documented convention (eg always calling `sprintf(cellfmt, beta, se, tsat, pval, stars)` in that order), there's a lot of flexibility inside printf using positional formats and such. Or you could make up a mini-format that works better for you.

**Comment by leifeld** [comment]
> Thanks, the workaround you provided of manually editing the object is good enough, for me, for now. My current client is targeting a journal that wants `$beta ($p.val) $stars` format, so it's easy enough to modify your workaround and call it good.
> 
> `tstats.to.se=TRUE` seems too narrow and somewhat confusing when you read it out loud, and `se.type='pval'` would be confusing at first glance also.
> 
> If you were going to make this configurable, I would recommend a more general refactor of letting the user pass in a format string, eg `cellfmt='%d (%d) %s'`, or some other description what they want, rather than adding a feature that is pretty specific and could easily become tech-debt long term.
> 
> If there were a documented convention (eg always calling `sprintf(cellfmt, beta, se, tsat, pval, stars)` in that order), there's a lot of flexibility inside printf using positional formats and such. Or you could make up a mini-format that works better for you.

Thanks for the suggestions. Having very flexible formats would likely cause trouble for decimal point alignment with the dcolumn and siunitx arguments. It's also unclear how to accommodate confidence intervals since they are value pairs and have square brackets. But I'll give it some thought.

**Comment by VeroBordeaux** [comment]
> Hi Everyone! This thread was opened a few years ago, and there have been many changes in the meantime that have made `texreg` much more complex than before with regard to its arguments and customizability. Given these developments, having arbitrary additional values and parentheses as suggested in my earlier comment seems like a very hard thing to implement if I want to take into account all those arguments and exceptions.
> 
> As a consequence, having a tweak to `texreg` like adding a `tstats.to.se` or a `pval.to.se` argument or perhaps an `se.type` argument with values `se`, `tstats`, and `pval` may seem more realistic. Then coef/se or pval could be reported in parentheses instead of the SE. Is this something that people would find useful? If so, please comment here.
> 
> Alternatively, you may just want to go via an intermediate `texreg` object, which is also reasonably easy to accomplish, like in the following example. The application is taken from the `lm` help page:
> 
> ```r
> library("texreg")
> 
> ctl <- c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14)
> trt <- c(4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69)
> group <- gl(2, 10, 20, labels = c("Ctl","Trt"))
> weight <- c(ctl, trt)
> lm.D9 <- lm(weight ~ group)
> 
> tr <- extract(lm.D9)
> tr@se <- tr@coef / tr@se
> tr@pvalues <- numeric()
> screenreg(list(lm.D9, tr), custom.model.names = c("Original", "t-stats"))
> ```
> 
> The output looks like this:
> 
> ```
> ===============================
>              Original   t-stats
> -------------------------------
> (Intercept)   5.03 ***    5.03 
>              (0.22)     (22.85)
> groupTrt     -0.37       -0.37 
>              (0.31)     (-1.19)
> -------------------------------
> R^2           0.07        0.07 
> Adj. R^2      0.02        0.02 
> Num. obs.    20          20    
> ===============================
> *** p < 0.001; ** p < 0.01; * p < 0.05
> ```
> 
> You can of course still show the p-values if you want, highlight significant coefficients in bold, use `single.row = TRUE` to display coefficient and t-statistics in the same row etc.
> 
> Would this solution work for folks here, or is it really necessary to have a separate argument for these things? Thanks for your feedback!

Hello
For me the first solution would be perfect. In  accounting review, we have to give coef, stars, t-stats and note se. 
Thanks a lot

**Comment by leifeld** [comment]
One could also do something like this if needed, though it's perhaps overkill:

``` r

tr.coef <- extract(lm.D9)
tr.coef@se <- numeric()
tr.coef@pvalues <- numeric()
tr.coef@model.name <- "coef"

tr.se <- extract(lm.D9)
tr.se@coef <- tr.se@se
tr.se@se <- numeric()
tr.se@pvalues <- numeric()
tr.se@model.name <- "SE"
tr.se@gof <- numeric()
tr.se@gof.decimal <- logical()
tr.se@gof.names <- character()

tr.tv <- extract(lm.D9)
tr.tv@coef <- tr.coef@coef / tr.tv@se
tr.tv@se <- numeric()
tr.tv@pvalues <- numeric()
tr.tv@model.name <- "t-stat"
tr.tv@gof <- numeric()
tr.tv@gof.decimal <- logical()
tr.tv@gof.names <- character()

tr.pv <- extract(lm.D9)
tr.pv@coef <- tr.pv@pvalues
tr.pv@se <- numeric()
tr.pv@pvalues <- numeric()
tr.pv@model.name <- "p-val"
tr.pv@gof <- numeric()
tr.pv@gof.decimal <- logical()
tr.pv@gof.names <- character()

screenreg(list(tr.coef, tr.se, tr.tv, tr.pv,
               tr.coef, tr.se, tr.tv, tr.pv),
          custom.header = list("Model 1" = 1:4,
                               "Model 2" = 5:8),
          custom.note = "")
```
Result:

```
===================================================================
                       Model 1                     Model 2         
             --------------------------  --------------------------
             coef   SE    t-stat  p-val  coef   SE    t-stat  p-val
-------------------------------------------------------------------
(Intercept)   5.03  0.22  22.85   0.00    5.03  0.22  22.85   0.00 
groupTrt     -0.37  0.31  -1.19   0.25   -0.37  0.31  -1.19   0.25 
-------------------------------------------------------------------
R^2           0.07                        0.07                     
Adj. R^2      0.02                        0.02                     
Num. obs.    20                          20                        
===================================================================
```
I'll close this for now but will re-open if I find a good way to make it more flexible.

**Comment by waynelapierre** [comment]
In my area, we always report t values under the coefficients. I have been using the stargazer package to get this done. You only need to add this argument report = "vc*t" to stargazer(), and you will get the t value replacing the se.
