### ISSUE TITLE
10% significance level in latex: `cdot` is invisible

### ISSUE THREAD

**Issue by photopresentr** [leifeld/texreg#53]
Sometimes, it is required for certain test to consider also significance levels beyond 5%. The `stars` parameter makes it easy to do this.

However, the symbol chosen by texreg's default for the 10% level -  `cdot` is nearly invisible. It looks like dirt on the screen or toner messed up on the page. While you may think that a result at the 10% level does not deserve more recognition, consider anyway to change the symbol.

Suggestion: `dagger` is used by other packages and more visible

**Comment by vincentarelbundock** [comment]
Just use the ``symbol`` argument.

```
> library(texreg)
> set.seed(1024)
> N = 10
> x = rnorm(N)
> y = x + rnorm(N)
> mod = lm(y ~ x)
> texreg(mod, stars = c(.001, .01, .05, .1), symbol = '\\dagger')

\begin{table}
\begin{center}
\begin{tabular}{l c }
\hline
 & Model 1 \\
\hline
(Intercept) & $-0.49$           \\
            & $(0.34)$          \\
x           &  $0.57^{\dagger}$ \\
            & $(0.27)$          \\
\hline
R$^2$       &   0.35            \\
Adj. R$^2$  &   0.27            \\
Num. obs.   &  10               \\
RMSE        &   1.06            \\
\hline
\multicolumn{2}{l}{\scriptsize{$^{***} p <0.001$; $^{**} p <0.01$; $^{*} p <0.05$; $^{\dagger} p <0.1$}}
\end{tabular}
\caption{Statistical models}
\label{table:coefficients}
\end{center}
\end{table}
>
```

@leifeld this issue should be closed.
