### ISSUE TITLE
multinom replicated model fit statistics multiple times

### ISSUE THREAD

**Issue by aserlich** [leifeld/texreg#56]
when outputing `multinom` models via `texreg()`, I get the same model fit statistics for all levels of the model. If you show one level at a time, then this doesn't occur, but if you want to show multiple levels of the dependent variable, then this is problematic.

**Comment by leifeld** [comment]
Thanks for the issue report. Would you mind providing a minimal self-contained example that demonstrates the actual and the desired behavior? Many thanks!

**Comment by aserlich** [comment]
```ml <- read.dta("https://stats.idre.ucla.edu/stat/data/hsbdemo.dta")
ml$prog2 <- relevel(ml$prog, ref = "academic")
test <- multinom(prog2 ~ ses + write, data = ml)

texreg(test)
```

As seen in the table below, this shows all of the model fit statistics twice. Since the model fit statistics pertain to the model, shouldn't they only be shown once probable in a LaTeX `multicolumn` environment?

Stat only outputs these model fit statistics once. Or am i missing something?
Thanks so much!


```
\begin{table}
\begin{center}
\begin{tabular}{l c c }
\hline
 & general & vocation \\
\hline
(Intercept)     & $2.85^{*}$   & $5.22^{***}$  \\
                & $(1.17)$     & $(1.16)$      \\
sesmiddle       & $-0.53$      & $0.29$        \\
                & $(0.44)$     & $(0.48)$      \\
seshigh         & $-1.16^{*}$  & $-0.98$       \\
                & $(0.51)$     & $(0.60)$      \\
write           & $-0.06^{**}$ & $-0.11^{***}$ \\
                & $(0.02)$     & $(0.02)$      \\
\hline
AIC             & 375.96       & 375.96        \\
BIC             & 402.35       & 402.35        \\
Log\ Likelihood & -179.98      & -179.98       \\
Deviance        & 359.96       & 359.96        \\
Num.\ obs.      & 200          & 200           \\
\hline
\multicolumn{3}{l}{\scriptsize{$^{***}p<0.001$, $^{**}p<0.01$, $^*p<0.05$}}
\end{tabular}
\caption{Statistical models}
\label{table:coefficients}
\end{center}
\end{table}


```
> packageVersion("texreg")
[1] ‘1.36.7’
```
