### ISSUE TITLE
Write to clipboard

### ISSUE THREAD

**Issue by kippjohnson** [leifeld/texreg#57]
First, thank you so much for this awesome package. It's been really helpful.

The main `texreg()` function contains some code that checks to see if the file output is a string, e.g.:

```
else if (!is.character(file)) {
    stop("The 'file' argument must be a character string.")
  } 
```
However, on Unix systems it is possible to copy directly to the clipboard. On Mac OS, it is as simple as `file=pipe('pbcopy')`. 

Would you accept a pull request enabling direct copy of the outputted code to the clipboard?

**Comment by leifeld** [comment]
Yes, sounds interesting. Please feel free to go ahead with this. Make sure you edit the help pages to reflect the change as well.

**Comment by leifeld** [comment]
I'll close this due to inactivity. I guess there are probably other ways in R to copy character objects (from the `texreg` function) or matrices (from the `matrixreg` function) to the clipboard.
