### ISSUE TITLE
Is there a 'no-math' mode?

### ISSUE THREAD

**Issue by christophsax** [leifeld/texreg#58]
Thanks for this nice package!

If I use a text font that is different from the math font, my `texreg` fonts are inconsistent:

<img width="430" alt="untitled copy" src="https://user-images.githubusercontent.com/1390827/29418773-92361c8c-836d-11e7-8b56-46cd5a786972.png">

I can `gsub`-out the math stuff like `$` and `^` from the `texreg` output but I wonder if there is an option to get this out of the box, something like a 'no-math' mode?

**Comment by czucca** [comment]
I'm not sure this is what you are asking, but if you set `dcolumn = TRUE ` it will remove the math symbols such as $. It won't remove ^ but I think you still need that for the stars. 

Hope this helps, 
C.
