### ISSUE TITLE
Swap rows with columns

### ISSUE THREAD

**Issue by string-token** [leifeld/texreg#63]
Sometimes, it is convenient to change the rows containing the coefficients and goodness of fit statistics with the columns containing the models. This is for example interesting if you compare many models which means you are focusing first of all only on gofs and you omit all specific coefs.

Model | L2 | df | p | BIC |  
-------|----|---|---|-----|
NA | 42,970 | 64 | .000 | 42,225 |
Q0 | 1,500 | 61 | .000 | 790 |
Qx | 956 | 46 | .000 | 421 |
...  | ... | ... | ... | ... |

Would it be possible to do produce such a table with texreg?

PS: Results from the package `gnm` follow the same pattern as `glm`. Thus you could add `setMethod("extract", signature = className("gnm", "gnm"), definition = extract.glm)` to `extract.R`. Often, one would produce some additional results using gnm's function `getContrasts`. I am not sure but possibly the easiest way to implement these additional results is to manually adjust the texreg object.

**Comment by leifeld** [comment]
I still haven't come across a real-world scenario where I would have found such a feature useful. I'll close this issue for now. If there is more demand for this, perhaps we can re-open the issue and reconsider. `gnm` objects have been added to `texreg`, meanwhile.
