### ISSUE TITLE
tidyr::extract conflict

### ISSUE THREAD

**Issue by drexell0680** [leifeld/texreg#66]
Hi there, 

Great package, I've been using it to do some gnls tables recently...  If I have the `tidyr` package loaded before I define my `extract.gnls` method (using `setMethod` to define), I run into an error as `extract` is a standard generic already defined and exported by tidyr.

Is there a good workaround for this?

Thanks,
Dan

**Comment by czucca** [comment]
Hi Dan, 

I've sent a pull request that adds an extract function for gnls objects, so you don't need to customise the `extract` function any more. 

For what concerns the question about extract, possibly I'm not understanding but have you tried calling `tidyr::extrac`t if you want the `extract` from `tidyr`? In texreg extract alone is not a function, you always have extract.[object]. So I don't see how they can conflict. 

I hope this helps, 
C.

**Comment by czucca** [comment]
closed by PR #leifeld94
