### ISSUE TITLE
add support for `speedglm` and `speedlm` 

### ISSUE THREAD

**Issue by xinluwang** [leifeld/texreg#68]
It is a great pleasure to use `texreg` package, but recently I need use the `speedglm` to run Poisson regression since it is developed recently thus sadly not supported by by `texreg`, would you consider to add it? Thank you！

**Comment by balachia** [comment]
@xinluwang, or anyone who finds this in the future: `speedlm`/`speedglm` appears to produce an object with similar structure to `lm`/`glm`. Running `texreg::extract.glm` directly on a speedglm result object appears to work properly. So e.g. this code should work:

```
model1 <- speedglm(y~x, data)
model2 <- speedglm(y~z, data)
list.of.models <- lapply(list(model1, model2), texreg::extract.glm)

texreg(list.of.models)
```

Unfortunately this doesn't work with the similar `biglm`...
