### ISSUE TITLE
Add option for exporting without tabular for texreg

### ISSUE THREAD

**Issue by christophe-gouel** [leifeld/texreg#72]
The possibility of customizing tables in latex is nearly infinite, so it should not be expected that all the possible options will ever be added to texreg. Several open issues relate to this kind of enhancements: #2, #3, or #25.

An easier approach would be to add an option (e.g., tabular = FALSE) for exporting just what is inside the tabular environment: the coefficients and GOF. Experienced LaTeX users each have their own habits when building tables and it may be faster for them to copy/paste the table and tabular environments from previous tables than to understand from texreg options how to generate tables in their own way.

I did it for my own use in <https://github.com/christophe-gouel/texreg>. Let me know if you want a pull request.

**Comment by czucca** [comment]
This has been addressed by the update in September.

**Comment by lukaskawerau** [comment]
How was this addressed? I can't seem to find documentation or other related information for this.

**Comment by leifeld** [comment]
I think the `matrixreg` function may be doing this?

**Comment by czucca** [comment]
Exactly

**Comment by christophe-gouel** [comment]
That’s perfect.

 

Thank you very much,

Christophe

 

De : Philip Leifeld <notifications@github.com> 
Envoyé : jeudi 28 mai 2020 17:44
À : leifeld/texreg <texreg@noreply.github.com>
Cc : Christophe Gouel <christophe.gouel@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [leifeld/texreg] Add option for exporting without tabular for texreg (#72)

 

Hi there. I have now added a new tabular argument, which is TRUE by default and leaves out the tabular environment if set to FALSE. This should make texreg tables more flexible because it can be combined with tabular*, tabularx etc. environments.
