### ISSUE TITLE
Stars argument is not muting stars on btergm results

### ISSUE THREAD

**Issue by calebpom** [leifeld/texreg#74]
Here's an example to reproduce the issue:

```
library(texreg)
library(xergm)


# lm example from Philip that works
ctl <- c(4.17,5.58,5.18,6.11,4.50,4.61,5.17,4.53,5.33,5.14)
trt <- c(4.81,4.17,4.41,3.59,5.87,3.83,6.03,4.89,4.32,4.69)
group <- gl(2,10,20, labels = c("Ctl","Trt"))
weight <- c(ctl, trt)
lm_test <- lm(weight ~ group)

screenreg(lm_test) # has stars, which is correct

screenreg(lm_test, stars = numeric(0)) # doesn't have stars, which is correct

texreg(lm_test, 
       stars = numeric(0), 
       bold=.05) # is bold with no stars, which is correct


# tergm example from documentation that doesn't work
set.seed(1912)

networks <- list()
for(i in 1:10){            # create 10 random networks with 10 actors
  mat <- matrix(rbinom(100, 1, .25), nrow = 10, ncol = 10)
  diag(mat) <- 0           # loops are excluded
  nw <- network(mat)       # create network object
  networks[[i]] <- nw      # add network to the list
}

covariates <- list()
for (i in 1:10) {          # create 10 matrices as covariate
  mat <- matrix(rnorm(100), nrow = 10, ncol = 10)
  covariates[[i]] <- mat   # add matrix to the list
}

tergm_test <- btergm(networks ~ edges + istar(2) +
                edgecov(covariates), R = 100)

screenreg(tergm_test) # has stars, which is correct

screenreg(tergm_test, stars = numeric(0)) # has stars, which is not correct

texreg(tergm_test, 
       stars = numeric(0), 
       bold=.05) # is bold and also has stars, which is not correct
```

I've only checked this for class `btergm` but other offenders might exist. Thanks!

**Comment by czucca** [comment]
Hi there,
if you use texreg/screenreg with btergm the argument "stars" does not make sense.  In fact, btergm extract function does not report significance, but confidence intervals. "stars" only mute the stars coming from a pvalue. The single star that you see in this output indicates whether the confidence interval contains zero or not, and it is not customisable with "stars". The argument "bold" is just reinforcing the meaning of the single star.
Hope this helps, 
C.

**Comment by calebpom** [comment]
Thanks for following up! That's all correct -- in the event of wanting to indicate significance (i.e. 0 outside the CI) using bold instead of stars, though, is it possible to mute the stars in order to avoid the simultaneous bold + stars (particularly when using `texreg`)? I was under the impression that that was possible (using `stars = 0`) even for a `btergm` object but could be mistaken.

Thanks for the help!

-Caleb

**Comment by czucca** [comment]
No at the moment it is not possible. CI does not allow you to mute stars. I'm gonna look into this!
Best, 
C.
