### ISSUE TITLE
Underscores in GOF for LaTeX

### ISSUE THREAD

**Issue by arcruz0** [leifeld/texreg#77]
Hi, thanks for the great package! I'm having problems with underscores in the LaTeX generated by texreg. The issue explained in #12 seems to be partially fixed, working fine for the variables names (see the OLS model below). However, when GOF names have underscores (for example, when they are generated from the variable names, as in the `extract.lme4()` method), the underscores are not escaped and the rendering fails. Here's a reprex, in RMarkdown:

````
---
title: "Reprex"
output: 
  pdf_document: 
    latex_engine: xelatex
---

```{r, message=F}
library(tidyverse)
library(lme4)
library(texreg)
```

```{r}
mtcars_df <- mtcars %>% 
  rownames_to_column() %>% 
  rename(var_mpg = mpg, var_disp = disp, var_am = am) %>% 
  select(rowname, starts_with("var"))

head(mtcars_df)
```
````

The following works fine:

````
```{r, results='asis'}
m_ols <- lm(var_mpg ~ var_disp + var_am, 
            data = mtcars_df)
texreg(m_ols)
```
````

The following fails with error `! Missing $ inserted. <inserted text> $ l.217 Num. groups: var_`:

````
```{r}
m_multilevel <- lmer(var_mpg ~ var_disp + (1|var_am), 
                     data = mtcars_df)
```

```{r, results='asis'}
texreg(m_multilevel)
```
````

While this, without the GOF names (but including the variable names), works fine:

````
```{r, results='asis'}
texreg(m_multilevel, include.groups = F, include.variance = F)
```


````

Thanks a lot!

**Comment by zauster** [comment]
I included a test for correct escaping of underscores in #100
