### ISSUE TITLE
Perl regular expression in internal func omit_rename

### ISSUE THREAD

**Issue by kanxu526** [leifeld/texreg#78]
Is it possible to have `perl = TRUE` for `omit_rename` so that we can use perl regular expression? 

The reason is that I want to keep a couple of variables, instead of choosing variable to delete, like in STATA (I would be really happy if there is an option to keep variables), so that I need to use perl regular expression to omit those variables that are not among some specific strings.

**Comment by nfultz** [comment]
I have just encountered this issue also, it would be very useful.  I have some high cardinality factors, and want to generate separate tables for each variable.

I am trying to write a pattern using negative lookahead to negate the match, eg 

```
omit.coef = "^(?!(Z_)?G[.])"
``` 

which would match everything except the coefficients beginning with "Z_G." and "G.".

The line to amend is here:
   https://github.com/leifeld/texreg/blob/master/R/internal.R#L494
