### ISSUE TITLE
Typo in the stars note for htmlreg

### ISSUE THREAD

**Issue by leifeld** [leifeld/texreg#8]
Comment by user [jonkeane](https://r-forge.r-project.org/users/jonkeane/) (Jonathan Keane) on R-Forge:

I noticed that there is a typo in the stars note for html format when there are 4 levels. This results in an extra tag being shown in the html output.

```
line 976 in texreg.R currently is :
star.symbol, star.symbol, "</sup", css.sup, ">p &lt; ", st[2],
but it looks like it should be:
star.symbol, star.symbol, "</sup>p &lt; ", st[2],
```

I've tried this change, and the output looks good to me.

**Comment by vincentarelbundock** [comment]
This is fixed by https://github.com/leifeld/texreg/pull/44
